from pathlib import Path

from blueprint_ai.adapters import applicable_adapters
from blueprint_ai.blueprints import BLUEPRINTS
from blueprint_ai.core import Finding
from blueprint_ai.core.priority import deduplicate
from blueprint_ai.discovery import discover_project
from blueprint_ai.engine import make_context, review
from blueprint_ai.model.context import ContextBuilder


def write(root: Path, path: str, text: str) -> None:
    file = root / path
    file.parent.mkdir(parents=True, exist_ok=True)
    file.write_text(text)


def test_nested_components_do_not_learn_roles_from_fixtures(tmp_path: Path) -> None:
    write(
        tmp_path, "backend/pyproject.toml", '[project]\nname="backend"\ndependencies=["fastapi"]\n'
    )
    write(tmp_path, "frontend/package.json", '{"name":"web","dependencies":{"react":"*"}}')
    write(tmp_path, "fixtures/requirements.txt", "# autogenerated\napache-airflow\ncrewai\n")
    write(tmp_path, "frontend/Sparkles.svelte", "<h1>Sparkles</h1>")
    facts = discover_project(tmp_path)
    assert {"full-stack", "api", "web-app"} <= set(facts.project_types)
    assert not {"ai-agent", "data-pipeline"} & set(facts.project_types)
    owner = facts.graph.owner("backend/service.py")
    assert owner is not None and owner.id == "backend"
    assert facts.graph.scope("fixtures/requirements.txt") == "fixture"


def test_requirements_comments_are_not_dependencies(tmp_path: Path) -> None:
    write(
        tmp_path,
        "requirements.txt",
        "# autogenerated by a tool\nFlask==3.1.0 \\\n --hash=sha256:abc\n",
    )
    facts = discover_project(tmp_path)
    assert "flask" in facts.frameworks
    assert "ai-agent" not in facts.project_types
    assert not facts.graph.diagnostics


def test_library_identity_and_documentation_lifecycle(tmp_path: Path) -> None:
    write(tmp_path, "pyproject.toml", '[project]\nname="Flask"\n[build-system]\nrequires=[]\n')
    write(tmp_path, "src/flask/__init__.py", "value = 1\n")
    facts = discover_project(tmp_path)
    assert facts.graph.lifecycle == "library-framework"
    assert not any(
        f.category == "invalid-package-name" for f in BLUEPRINTS["identity"].check(tmp_path, facts)
    )
    docs = tmp_path / "docs-only"
    write(docs, "README.md", "# A curated list\n")
    write(docs, ".github/workflows/ci.yml", "name: Lint\non: push\njobs: {}\n")
    context, _ = make_context(docs, model_mode="off")
    assert context.profiles == ["documentation-project"]
    assert "testing" not in context.selected_blueprints


def test_workspace_and_inline_verification_inventory(tmp_path: Path) -> None:
    write(tmp_path, "Cargo.toml", '[workspace]\nmembers=["crates/*"]\n')
    write(tmp_path, "crates/engine/Cargo.toml", '[package]\nname="engine"\nversion="0.1.0"\n')
    write(tmp_path, "crates/engine/src/lib.rs", "#[test]\nfn works() { assert_eq!(1,1); }\n")
    graph = discover_project(tmp_path).graph
    assert any(
        e.kind == "workspace-member" and e.target == "crates/engine" for e in graph.relationships
    )
    assert any(v.kind == "unit" and v.component == "crates/engine" for v in graph.verification)


def test_hcl_module_graph_and_cloud_are_parsed(tmp_path: Path) -> None:
    write(
        tmp_path,
        "main.tf",
        """variable "enabled" { default = false }
module "vpc" { source = "terraform-aws-modules/vpc/aws" version = "6.0.0" }
resource "aws_vpc" "main" { count = var.enabled ? 1 : 0 cidr_block = "10.0.0.0/16" }
""",
    )
    facts = discover_project(tmp_path)
    assert facts.cloud_hints == ["aws"]
    assert facts.graph.lifecycle == "reusable-infrastructure-module"
    assert facts.graph.relationships[0].external
    assert facts.graph.components[0].dependencies[0].name == "terraform-aws-modules/vpc/aws"
    assert not facts.graph.diagnostics


def test_module_tool_routing_and_fixture_exclusion(tmp_path: Path) -> None:
    for component in ("one", "two"):
        write(tmp_path, f"{component}/pyproject.toml", f'[project]\nname="{component}"\n')
        write(tmp_path, f"{component}/app.py", "import os\n")
        write(tmp_path, f"{component}/tests/fixtures/invalid.py", "invalid : :\n")
    adapters = applicable_adapters(discover_project(tmp_path), "code-quality")
    ruffs = [a for a in adapters if a.name.startswith("ruff")]
    assert {a.working_directory for a in ruffs} == {"one", "two"}
    assert all(
        "--no-cache" in a.args and not any("invalid.py" in arg for arg in a.args) for a in ruffs
    )


def test_rust_fixtures_do_not_trigger_python_linter(tmp_path: Path) -> None:
    write(tmp_path, "Cargo.toml", '[package]\nname="compiler"\nversion="0.1.0"\n')
    write(tmp_path, "src/lib.rs", "pub fn parse() {}\n")
    write(tmp_path, "tests/fixtures/a.py", "bad syntax invalid\n")
    assert not any(
        a.name == "ruff" for a in applicable_adapters(discover_project(tmp_path), "code-quality")
    )


def test_dependency_alias_merge_keeps_package_scope_and_evidence() -> None:
    rows = []
    for file, rule, aliases in (
        ("uv.lock", "GHSA-aaaa-bbbb-cccc", ["CVE-2025-12345"]),
        ("requirements.txt", "PYSEC-2025-99", ["GHSA-aaaa-bbbb-cccc"]),
    ):
        rows.append(
            Finding(
                blueprint="supply-chain",
                category="dependency-vulnerability",
                source="osv",
                message=rule,
                recommendation="Upgrade",
                rule_id=rule,
                file=file,
                component="backend",
                advisory_aliases=aliases,
                locations=[file],
                tool_metadata={"package": "foo", "ecosystem": "PyPI", "installed_version": "1"},
            )
        )
    distinct = rows[0].model_copy(deep=True)
    distinct.tool_metadata["package"] = "bar"
    rows.append(distinct)
    merged = deduplicate(rows, [])
    assert len(merged) == 2
    assert len({item.fingerprint for item in merged}) == 2
    assert next(r for r in merged if r.tool_metadata["package"] == "foo").locations == [
        "requirements.txt",
        "uv.lock",
    ]


def test_conventional_policy_paths_and_local_workflow(tmp_path: Path) -> None:
    write(tmp_path, "LICENSE.txt", "license")
    write(tmp_path, "docs/SECURITY.md", "# Security")
    write(tmp_path, ".github/contributing.md", "# Contributing")
    write(tmp_path, "README.md", "# Example\nHow to Use\n")
    write(
        tmp_path,
        ".github/workflows/ci.yml",
        "name: CI\non: push\njobs:\n  test:\n    uses: $/.github/workflows/test.yml\n",
    )
    facts = discover_project(tmp_path)
    assert not any(
        f.category == "unpinned-action" for f in BLUEPRINTS["ci-cd"].check(tmp_path, facts)
    )
    assert not any(
        f.file in {"LICENSE", "SECURITY.md", "CONTRIBUTING.md"}
        for f in BLUEPRINTS["repository"].check(tmp_path, facts)
    )
    assert not BLUEPRINTS["documentation"].check(tmp_path, facts)


def test_documented_corpora_and_benchmark_resources_are_not_runtime(tmp_path: Path) -> None:
    write(
        tmp_path, "Cargo.toml", '[package]\nname="compiler"\nversion="1"\n[[bench]]\nname="speed"\n'
    )
    write(
        tmp_path, "resources/workload.py", "import requests\nrequests.get('https://example.org')\n"
    )
    write(tmp_path, "README.md", "The truth data in ./truth uses <CURSOR> markers.\n")
    write(tmp_path, "truth/project/pyproject.toml", '[project]\nname="fixture"\n')
    write(tmp_path, "truth/project/input.py", "<CURSOR>\n")
    facts = discover_project(tmp_path)
    assert facts.graph.scope("resources/workload.py") == "benchmark"
    owner = facts.graph.owner("truth/project/input.py")
    assert owner is not None and owner.scope == "fixture"
    assert not any(
        f.category == "missing-timeout" for f in BLUEPRINTS["reliability"].check(tmp_path, facts)
    )


def test_remote_module_scanning_does_not_authorize_target_urls(tmp_path: Path) -> None:
    write(tmp_path, "main.tf", 'module "private" { source="http://127.0.0.1/module.zip" }\n')
    tools = applicable_adapters(discover_project(tmp_path), "iac")
    trivy = next(t for t in tools if t.name == "trivy")
    assert trivy.disabled_reason and "network authorization" in trivy.disabled_reason


def test_generated_contract_relationship_is_hash_bound(tmp_path: Path) -> None:
    import hashlib
    import json

    write(tmp_path, "backend/openapi.json", "{}\n")
    write(tmp_path, "frontend/src/generated/api.d.ts", 'export type Health = "ok"\n')
    paths = ["backend/openapi.json", "frontend/src/generated/api.d.ts"]
    hashes = {p: hashlib.sha256((tmp_path / p).read_bytes()).hexdigest() for p in paths}
    write(
        tmp_path,
        ".blueprint-ai/genesis.json",
        json.dumps(
            {
                "schema_version": "1.0",
                "result": {"files": hashes},
                "graph": {
                    "relationships": [
                        {
                            "source": paths[0],
                            "target": paths[1],
                            "kind": "generated-client",
                            "evidence": {"file": paths[0], "kind": "provider", "detail": "test"},
                        }
                    ]
                },
            }
        ),
    )
    graph = discover_project(tmp_path).graph
    assert any(e.kind == "generated-client" for e in graph.relationships)
    write(tmp_path, paths[1], 'export type Health = "changed"\n')
    graph = discover_project(tmp_path).graph
    assert not any(e.kind == "generated-client" for e in graph.relationships)
    assert any("drift" in diagnostic for diagnostic in graph.diagnostics)


def test_large_context_reserves_real_source_and_deduplicates_reads(tmp_path: Path) -> None:
    for i in range(220):
        write(tmp_path, f"component{i}/pyproject.toml", f'[project]\nname="component{i}"\n')
        write(
            tmp_path, f"component{i}/app.py", f"def calculate_{i}(value):\n    return value * {i}\n"
        )
    write(tmp_path, "tests/test_invariant.py", "def test_invariant():\n    assert 2 + 2 == 4\n")
    facts = discover_project(tmp_path)
    builder = ContextBuilder(tmp_path, 2000)
    architecture = builder.build("architecture", facts, [])
    testing = builder.build("testing", facts, [])
    assert "BEGIN_UNTRUSTED_FILE" in architecture and "def calculate_" in architecture
    assert "test_invariant" in testing
    assert architecture != testing
    assert len(architecture) <= 8000 and len(testing) <= 8000
    assert builder.metrics["files_read"] <= 48
    before = builder.metrics["files_read"]
    assert builder.build("testing", facts, []) == testing
    assert builder.metrics["files_read"] == before


def test_review_is_read_only_with_real_ruff(tmp_path: Path) -> None:
    write(tmp_path, "pyproject.toml", '[project]\nname="sample"\n')
    write(tmp_path, "app.py", "import os\n")
    before = sorted(p.relative_to(tmp_path).as_posix() for p in tmp_path.rglob("*"))
    context, _ = make_context(tmp_path, blueprints=["code-quality"], model_mode="off")
    result = review(context)
    assert any(t.name == "ruff" and t.outcome == "finding" for r in result.results for t in r.tools)
    assert before == sorted(p.relative_to(tmp_path).as_posix() for p in tmp_path.rglob("*"))
    assert result.metadata and result.metadata.analyzer_source_sha256
