"""Phase 8 authoritative migration-pipeline and adversarial regressions."""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest
from pydantic import ValidationError

from blueprint_ai.evolution import (
    TRANSFORMATIONS,
    accept_evolution,
    apply_evolution,
    plan_evolution,
    project_fingerprint,
    rollback_evolution,
)
from blueprint_ai.evolution.catalog import (
    OFFICIAL_ACTION_SHAS,
    _add_setuptools_build_system,
    _javascript_code_mask,
    _javascript_migration_syntax_mask,
    _next_experimental_ppr_residual,
    _next_font_residual,
    _next_unsafe_unwrapped_residual,
    _next_unstable_cache_residual,
    _repair_react_this_refs,
    _replace_dotnet_tfm,
    _replace_rust_edition,
)
from blueprint_ai.evolution.models import (
    AuthoritativeToolContract,
    ResidualContract,
)
from blueprint_ai.sandbox import SandboxPolicy


def _git(root: Path, *arguments: str) -> str:
    result = subprocess.run(
        ["git", "-C", str(root), *arguments],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def _repository(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    for relative, content in files.items():
        destination = root / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content)
    _git(root, "init", "-b", "phase8")
    _git(root, "config", "user.email", "tests@blueprint.invalid")
    _git(root, "config", "user.name", "Blueprint Tests")
    _git(root, "add", ".")
    _git(root, "commit", "-m", "fixture")
    return root


def _rust_files(edition: str) -> dict[str, str]:
    return {
        "Cargo.toml": (f'[package]\nname = "demo"\nversion = "0.1.0"\nedition = "{edition}"\n'),
        "Cargo.lock": "# This file is automatically @generated by Cargo.\nversion = 4\n",
        "src/lib.rs": "/// Answer.\npub fn answer() -> u8 { 42 }\n",
    }


def test_phase8_schemas_are_sealed_and_agent_backend_is_absent() -> None:
    contract = TRANSFORMATIONS["rust/edition"].spec.tool_contract
    assert isinstance(contract, AuthoritativeToolContract)
    assert contract.distribution == "invoke" and not contract.redistribution_permitted
    assert contract.image and contract.expected_write_scopes
    with pytest.raises(ValidationError):
        AuthoritativeToolContract.model_validate(
            {**contract.model_dump(), "arbitrary_command": ["sh", "-c", "anything"]}
        )
    residual = ResidualContract(
        desired_state=["compile on net10.0"],
        completed_steps=["target-framework"],
        failures=["API X is unavailable"],
        permitted_paths=["Program.cs"],
        constraints=["preserve public behavior"],
        prohibited_scope=["dependencies", "deployment"],
        acceptance_commands=[["dotnet", "test"]],
        postconditions=[],
        command_allowlist=["dotnet"],
        credential_requirements=[],
        timeout_seconds=600,
        step_limit=5,
        token_limit=20_000,
        rollback_checkpoint="sha256:" + "a" * 64,
    )
    assert residual.permitted_paths == ["Program.cs"]
    assert residual.credential_requirements == []
    assert all("AgentBackend" not in path.read_text() for path in Path("src").rglob("*.py"))


def test_rust_2018_to_2024_is_two_ordered_boundaries(tmp_path: Path) -> None:
    root = _repository(tmp_path / "rust", _rust_files("2018"))
    plan = plan_evolution(root, ["rust/edition=2024"])
    assert plan.status == "ready" and plan.target_versions == {"rust/edition": "2024"}
    assert [step.operation for step in plan.steps] == [
        "cargo-fix-2021",
        "rust-edition",
        "cargo-fmt-2021",
        "verify-2021",
        "cargo-fix-2024",
        "rust-edition",
        "cargo-fmt-2024",
        "verify-2024",
    ]
    assert [step.operation_target for step in plan.steps if step.kind == "builtin-edit"] == [
        "2021",
        "2024",
    ]
    assert all(
        not step.depends_on or step.depends_on == [plan.steps[index - 1].id]
        for index, step in enumerate(plan.steps)
    )
    assert sum(step.rediscover for step in plan.steps) == 4


def test_rust_dependency_acquisition_and_binary_target_verification(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "rust-dependency",
        {
            "Cargo.toml": (
                '[package]\nname = "demo"\nversion = "0.1.0"\nedition = "2021"\n'
                '[dependencies]\nanyhow = "1.0.100"\n'
            ),
            "Cargo.lock": "version = 4\n",
            "src/main.rs": 'fn main() { println!("ok"); }\n',
        },
    )
    plan = plan_evolution(root, ["rust/edition=2024"])
    assert plan.steps[0].kind == "dependency-acquisition"
    assert plan.steps[0].files == []
    assert plan.steps[0].execution_network == "required"
    assert plan.steps[0].apply_command[:3] == ["cargo", "vendor", "--locked"]
    assert any(step.operation == "cargo-fmt-2024" for step in plan.steps)
    assert all(
        requirement.kind != "doctest" for step in plan.steps for requirement in step.verification
    )

    unsupported = _repository(
        tmp_path / "rust-git-dependency",
        {
            "Cargo.toml": (
                '[package]\nname = "demo"\nversion = "0.1.0"\nedition = "2021"\n'
                '[dependencies]\nexample = { git = "https://example.invalid/repo" }\n'
            ),
            "Cargo.lock": "version = 4\n",
            "src/lib.rs": "pub fn demo() {}\n",
        },
    )
    assert "rust/edition" not in plan_evolution(unsupported).candidates


def test_rust_lane_rejects_inherited_workspace_and_edits_only_package_table(
    tmp_path: Path,
) -> None:
    workspace = _repository(
        tmp_path / "workspace",
        {
            "Cargo.toml": (
                '[workspace]\nmembers = ["member"]\n[workspace.package]\nedition = "2018"\n'
            ),
            "Cargo.lock": "version = 4\n",
            "member/Cargo.toml": (
                '[package]\nname = "member"\nversion = "0.1.0"\nedition.workspace = true\n'
            ),
            "member/src/lib.rs": "pub fn member() {}\n",
        },
    )
    assert "rust/edition" not in plan_evolution(workspace).candidates

    root = _repository(
        tmp_path / "metadata",
        {
            **_rust_files("2018"),
            "Cargo.toml": (
                '[package]\nname = "demo"\nversion = "0.1.0"\nedition = "2018"\n'
                '[package.metadata.docs]\nedition = "2018"\n'
            ),
        },
    )
    rendered = _replace_rust_edition(root, ["Cargo.toml"], "2021")["Cargo.toml"]
    assert 'edition = "2021"' in rendered
    assert '[package.metadata.docs]\nedition = "2018"' in rendered


def test_rust_lane_rejects_independent_nested_packages(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "nested-rust",
        {
            **_rust_files("2018"),
            "child/Cargo.toml": (
                '[package]\nname = "child"\nversion = "0.1.0"\nedition = "2018"\n'
            ),
            "child/src/lib.rs": "this is invalid rust syntax !!!\n",
        },
    )
    plan = plan_evolution(root, ["rust/edition=2024"])
    assert "rust/edition" not in plan.candidates
    assert plan.status == "blocked" and plan.steps[0].status == "failed-precondition"


def test_rust_lane_seals_integration_test_targets(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "rust-tests",
        {
            **_rust_files("2018"),
            "tests/edition.rs": "trait T {}\nfn borrow(_: &T) {}\n#[test]\nfn ok() {}\n",
        },
    )
    plan = plan_evolution(root, ["rust/edition=2021"])
    assert plan.status == "ready"
    assert "tests/edition.rs" in plan.steps[0].files
    assert "tests/edition.rs" in plan.steps[2].files


def test_rust_targets_decision_current_and_unsupported_controls(tmp_path: Path) -> None:
    old = _repository(tmp_path / "old", _rust_files("2021"))
    decision = plan_evolution(old, ["rust/edition"])
    assert decision.status == "blocked" and decision.steps[0].status == "manual"
    with pytest.raises(ValueError, match="unsupported target"):
        plan_evolution(old, ["rust/edition=2027"])
    current = _repository(tmp_path / "current", _rust_files("2024"))
    noop = plan_evolution(current, ["rust/edition=2024"])
    assert noop.status == "noop" and "rust/edition" not in noop.candidates


def test_simple_dotnet_lane_preserves_unrelated_xml_and_rejects_ambiguity(
    tmp_path: Path,
) -> None:
    source = (
        '<Project Sdk="Microsoft.NET.Sdk">\n'
        "  <!-- preserve me -->\n"
        "  <PropertyGroup><Nullable>enable</Nullable>"
        "<TargetFramework>net6.0</TargetFramework></PropertyGroup>\n"
        "</Project>\n"
    )
    root = _repository(tmp_path / "simple", {"Demo.csproj": source, "Program.cs": ""})
    plan = plan_evolution(root, ["dotnet/sdk-target=net10.0"])
    assert [step.operation for step in plan.steps] == ["dotnet-tfm", "command"]
    rendered = _replace_dotnet_tfm(root, ["Demo.csproj"], "net10.0")["Demo.csproj"]
    assert rendered == source.replace("net6.0", "net10.0")
    ambiguous = _repository(
        tmp_path / "ambiguous",
        {
            "Demo.csproj": (
                '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
                "<TargetFrameworks>net6.0;net8.0</TargetFrameworks>"
                "</PropertyGroup></Project>"
            )
        },
    )
    assert "dotnet/sdk-target" not in plan_evolution(ambiguous).candidates
    conditional = _repository(
        tmp_path / "conditional",
        {
            "Demo.csproj": (
                '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
                "<TargetFramework Condition=\"'$(Configuration)' == 'Debug'\">net6.0"
                "</TargetFramework></PropertyGroup></Project>"
            )
        },
    )
    assert "dotnet/sdk-target" not in plan_evolution(conditional).candidates


@pytest.mark.parametrize("sdk", ["Microsoft.NET.Sdk", "Microsoft.NET.Sdk.Web"])
def test_dotnet_exact_packages_use_an_explicit_acquisition_stage(tmp_path: Path, sdk: str) -> None:
    root = _repository(
        tmp_path / sdk.rsplit(".", 1)[-1],
        {
            "Demo.csproj": (
                f'<Project Sdk="{sdk}"><PropertyGroup>'
                "<TargetFramework>net7.0</TargetFramework></PropertyGroup>"
                '<ItemGroup><PackageReference Include="Example.Package" Version="1.2.3" />'
                "</ItemGroup></Project>"
            ),
            "Program.cs": 'Console.WriteLine("hello");\n',
        },
    )
    plan = plan_evolution(root, ["dotnet/sdk-target=net10.0"])
    assert [step.operation for step in plan.steps] == [
        "dotnet-tfm",
        "dotnet-restore",
        "command",
    ]
    acquisition = plan.steps[1]
    assert acquisition.kind == "dependency-acquisition"
    assert acquisition.files == []
    assert acquisition.execution_network == "required"
    assert acquisition.apply_command[:3] == ["dotnet", "restore", "Demo.csproj"]
    assert acquisition.apply_command[acquisition.apply_command.index("--source") + 1] == (
        "https://api.nuget.org/v3/index.json"
    )
    assert acquisition.ephemeral_paths == [".blueprint-state"]
    assert plan.steps[2].verification[0].isolated_copy


def test_dotnet_nested_project_seals_both_intermediate_path_bases(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "nested-dotnet",
        {
            "src/Demo.csproj": (
                '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
                "<TargetFramework>net8.0</TargetFramework></PropertyGroup>"
                '<ItemGroup><PackageReference Include="Example" Version="1.2.3" />'
                "</ItemGroup></Project>"
            ),
            "src/Program.cs": 'Console.WriteLine("hello");\n',
        },
    )
    plan = plan_evolution(root, ["dotnet/sdk-target=net10.0"])
    assert plan.steps[1].ephemeral_paths == [".blueprint-state", "src/.blueprint-state"]


def test_dotnet_rejects_floating_or_conditioned_package_references(tmp_path: Path) -> None:
    for name, reference in {
        "floating": '<PackageReference Include="Example" Version="1.*" />',
        "conditioned": ('<PackageReference Include="Example" Version="1.2.3" Condition="true" />'),
    }.items():
        root = _repository(
            tmp_path / name,
            {
                "Demo.csproj": (
                    '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
                    "<TargetFramework>net7.0</TargetFramework></PropertyGroup>"
                    f"<ItemGroup>{reference}</ItemGroup></Project>"
                )
            },
        )
        assert "dotnet/sdk-target" not in plan_evolution(root).candidates

    parent_condition = _repository(
        tmp_path / "conditioned-item-group",
        {
            "Demo.csproj": (
                '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>'
                "<TargetFramework>net7.0</TargetFramework></PropertyGroup>"
                '<ItemGroup Condition="true">'
                '<PackageReference Include="Example" Version="1.2.3" />'
                "</ItemGroup></Project>"
            )
        },
    )
    assert "dotnet/sdk-target" not in plan_evolution(parent_condition).candidates


def test_python_build_system_is_minimal_preserving_and_conflict_aware(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "legacy",
        {
            "setup.py": "from setuptools import setup\nsetup()\n",
            "setup.cfg": "[metadata]\nname = demo\n",
        },
    )
    plan = plan_evolution(root, ["python/pep517-build-system=setuptools.build_meta"])
    assert plan.status == "ready" and plan.steps[0].operation == "python-build-system"
    rendered = _add_setuptools_build_system(
        root, ["setup.py", "setup.cfg", "pyproject.toml"], "setuptools.build_meta"
    )["pyproject.toml"]
    assert rendered == (
        '[build-system]\nrequires = ["setuptools>=77"]\nbuild-backend = "setuptools.build_meta"\n'
    )
    assert (root / "setup.py").read_text() == "from setuptools import setup\nsetup()\n"
    conflict = _repository(
        tmp_path / "conflict",
        {
            "setup.py": "from setuptools import setup\nsetup()\n",
            "pyproject.toml": (
                '[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n'
            ),
        },
    )
    assert "python/pep517-build-system" not in plan_evolution(conflict).candidates
    flit = _repository(
        tmp_path / "flit",
        {
            "setup.py": "from setuptools import setup\nsetup()\n",
            "pyproject.toml": "[tool.flit.metadata]\nmodule = 'demo'\n",
        },
    )
    assert "python/pep517-build-system" not in plan_evolution(flit).candidates


def test_react_this_refs_repair_is_narrow_and_comment_string_safe(tmp_path: Path) -> None:
    root = tmp_path / "react-repair"
    root.mkdir()
    source = (
        "class Demo extends React.Component {\n"
        "  run() { this.refs.input.focus(); const s = 'this.refs.input'; }\n"
        "  render() { return <input ref={(node) => { this.refs.input = node; }} />; }\n"
        "}\n"
        "const pattern = /this.refs.input/;\n"
        "// this.refs.input stays documentary\n"
        "// ref={(node) => { this.refs.fake = node; }}\n"
        "const unrelated = this.refs.fake;\n"
    )
    (root / "Demo.jsx").write_text(source)
    result = _repair_react_this_refs(root, ["Demo.jsx"], None)["Demo.jsx"]
    assert "this.input.focus()" in result and "this.input = node" in result
    assert "'this.refs.input'" in result and "// this.refs.input" in result
    assert "/this.refs.input/" in result and "this.refs.fake" in result
    negative = "const x = this.refs.unrelated;\n"
    (root / "Negative.jsx").write_text(negative)
    assert _repair_react_this_refs(root, ["Negative.jsx"], None) == {}


def test_javascript_migration_syntax_exposes_only_contextual_literals() -> None:
    source = (
        "const fake = '<div ref=\"fake\" />';\n"
        '// const x = <div ref="comment" />;\n'
        'const real = <div ref="panel" />;\n'
        "const expression = <div ref={'expression'} />;\n"
        "import { Inter } from '@next/font/google';\n"
        "const documentary = 'from \"@next/font/fake\"';\n"
    )
    masked = _javascript_migration_syntax_mask(source)
    assert 'ref="panel"' in masked and "'expression'" in masked
    assert "'@next/font/google'" in masked
    assert 'ref="fake"' not in masked and 'ref="comment"' not in masked
    assert "@next/font/fake" not in masked


def test_javascript_code_mask_preserves_template_interpolation_apis() -> None:
    source = "const value = `${this.refs.panel} ${ReactDOM.render(app, root)}`;\n"
    masked = _javascript_code_mask(source)
    assert "this.refs.panel" in masked
    assert "ReactDOM.render" in masked


def test_react_recipe_without_preexecution_integrity_is_not_executable(tmp_path: Path) -> None:
    def files(version: str) -> dict[str, str]:
        return {
            "package.json": json.dumps({"dependencies": {"react": version, "react-dom": version}}),
            "src/App.jsx": "export default function App() { return <div />; }\n",
        }

    old = _repository(tmp_path / "react17", files("17.0.2"))
    blocked = plan_evolution(old, ["react/19-official-codemods=19.3.0"])
    assert [step.status for step in blocked.steps] == ["failed-precondition"]
    ready = _repository(tmp_path / "react18", files("18.3.1"))
    plan = plan_evolution(ready, ["react/19-official-codemods=19.3.0"])
    assert plan.status == "blocked"
    assert plan.steps[0].operation == "verified-recipe-acquisition"
    before = project_fingerprint(ready)
    with pytest.raises(ValueError, match="manual/deferred"):
        apply_evolution(ready, plan, run_blueprint_review=False)
    assert project_fingerprint(ready) == before


def test_next_14_to_16_uses_ordered_official_boundary_transforms(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "next",
        {
            "package.json": json.dumps(
                {
                    "scripts": {"lint": "next lint"},
                    "dependencies": {
                        "next": "14.2.0",
                        "@next/font": "14.2.0",
                        "react": "18.2.0",
                        "react-dom": "18.2.0",
                    },
                }
            ),
            "app/layout.tsx": "import { Inter } from '@next/font/google';\n",
        },
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    operations = [step.operation for step in plan.steps]
    assert operations == [
        "built-in-next-font-15-5-25",
        "next-async-request-api-15-5-25",
        "next-dependencies",
        "next-async-request-api-16-3-5",
        "next-lint-to-eslint-cli-16-3-5",
        "middleware-to-proxy-16-3-5",
        "remove-experimental-ppr-16-3-5",
        "remove-unstable-prefix-16-3-5",
        "next-dependencies",
        "project-verification",
    ]
    assert plan.steps[-1].status == "manual"
    assert all(
        not step.depends_on or step.depends_on == [plan.steps[index - 1].id]
        for index, step in enumerate(plan.steps)
    )
    assert all(step.rediscover for step in plan.steps if step.mutates)


def test_next_existing_yarn_lock_and_serial_codemods_remain_partial(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "next-yarn",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "14.2.35",
                        "react": "18.3.1",
                        "react-dom": "18.3.1",
                    }
                }
            ),
            "yarn.lock": "# yarn lockfile v1\n",
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=15.5.25"])
    assert plan.status == "ready"
    assert all(
        "yarn.lock" in step.files for step in plan.steps if step.kind == "established-codemod"
    )
    commands = [step.apply_command for step in plan.steps if step.kind == "established-codemod"]
    assert commands and all("--run-in-band" in command for command in commands)
    dependency = next(step for step in plan.steps if step.operation == "next-dependencies")
    assert any("no-unsafe-unwrapped" in item.id for item in dependency.postconditions)
    assert plan.steps[-1].status == "manual"


def test_next_exact_target_minor_and_unsafe_transform_states(tmp_path: Path) -> None:
    def next_files(version: str) -> dict[str, str]:
        return {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": version,
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/layout.tsx": "export default function Layout() { return null; }\n",
        }

    current = _repository(tmp_path / "current", next_files("15.5.25"))
    assert plan_evolution(current, ["next/official-upgrade-codemod=15.5.25"]).status == "blocked"
    current_16 = _repository(tmp_path / "current16", next_files("16.3.5"))
    assert plan_evolution(current_16, ["next/official-upgrade-codemod=16.3.5"]).status == "blocked"
    wrong_16 = _repository(tmp_path / "wrong16", next_files("16.0.0"))
    wrong_plan = plan_evolution(wrong_16, ["next/official-upgrade-codemod=16.3.5"])
    assert wrong_plan.status == "ready"
    assert [step.operation for step in wrong_plan.steps] == [
        "next-dependencies",
        "project-verification",
    ]
    minor = _repository(tmp_path / "minor", next_files("15.0.0"))
    minor_plan = plan_evolution(minor, ["next/official-upgrade-codemod=15.5.25"])
    assert [step.operation for step in minor_plan.steps] == [
        "next-dependencies",
        "project-verification",
    ]

    legacy = _repository(
        tmp_path / "legacy-eslint",
        {**next_files("15.5.25"), ".eslintrc.json": "{}\n"},
    )
    legacy_plan = plan_evolution(legacy, ["next/official-upgrade-codemod=16.3.5"])
    assert legacy_plan.status == "blocked"
    assert legacy_plan.steps[0].status == "failed-precondition"

    collision = _repository(
        tmp_path / "collision",
        {
            **next_files("15.5.25"),
            "middleware.ts": "export function middleware() {}\n",
            "proxy.ts": "export function proxy() {}\n",
        },
    )
    collision_plan = plan_evolution(collision, ["next/official-upgrade-codemod=16.3.5"])
    assert collision_plan.status == "blocked"
    assert collision_plan.steps[0].operation == "proxy-path-collision"

    rename = _repository(
        tmp_path / "rename",
        {**next_files("15.5.25"), "middleware.ts": "export function middleware() {}\n"},
    )
    rename_plan = plan_evolution(rename, ["next/official-upgrade-codemod=16.3.5"])
    codemod_steps = [step for step in rename_plan.steps if step.kind == "established-codemod"]
    assert codemod_steps and all(
        {"middleware.ts", "proxy.ts"} <= set(step.files) for step in codemod_steps
    )

    edge = _repository(
        tmp_path / "edge",
        {
            **next_files("15.5.25"),
            "middleware.ts": "export const runtime = 'edge';\nexport function middleware() {}\n",
        },
    )
    edge_plan = plan_evolution(edge, ["next/official-upgrade-codemod=16.3.5"])
    assert edge_plan.status == "blocked"
    assert edge_plan.steps[0].operation == "edge-middleware-runtime"

    mts = _repository(
        tmp_path / "mts",
        {**next_files("15.5.25"), "eslint.config.mts": "export default [];\n"},
    )
    mts_plan = plan_evolution(mts, ["next/official-upgrade-codemod=16.3.5"])
    assert all(
        "eslint.config.mts" in step.files
        for step in mts_plan.steps
        if step.kind == "established-codemod"
    )

    different_extension_collision = _repository(
        tmp_path / "different-extension-collision",
        {
            **next_files("15.5.25"),
            "middleware.ts": "export function middleware() {}\n",
            "proxy.js": "export function proxy() {}\n",
        },
    )
    collision_plan = plan_evolution(
        different_extension_collision, ["next/official-upgrade-codemod=16.3.5"]
    )
    assert collision_plan.status == "blocked"
    assert collision_plan.steps[0].operation == "proxy-path-collision"


def test_next_target_proof_is_structural_and_supports_src_app(tmp_path: Path) -> None:
    base = {
        "next": "16.3.5",
        "react": "19.3.0",
        "react-dom": "19.3.0",
    }
    clean = _repository(
        tmp_path / "clean",
        {
            "package.json": json.dumps(
                {"description": "Migration from next lint is complete", "dependencies": base}
            ),
            "src/app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    clean_plan = plan_evolution(clean, ["next/official-upgrade-codemod=16.3.5"])
    assert clean_plan.status == "blocked"
    assert clean_plan.steps[0].operation == "project-verification"

    stale_eslint = _repository(
        tmp_path / "stale-eslint",
        {
            "package.json": json.dumps(
                {
                    "dependencies": base,
                    "devDependencies": {"eslint-config-next": "15.5.25"},
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    assert plan_evolution(stale_eslint, ["next/official-upgrade-codemod=16.3.5"]).status == "ready"

    stale_font = _repository(
        tmp_path / "stale-font",
        {
            "package.json": json.dumps({"dependencies": {**base, "@next/font": "14.2.0"}}),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    assert plan_evolution(stale_font, ["next/official-upgrade-codemod=16.3.5"]).status == "ready"


@pytest.mark.parametrize(
    "source",
    [
        "import { unstable_cacheTag } from 'next/cache';\n",
        "export { unstable_cacheLife } from 'next/cache';\n",
        "const { unstable_cacheTag } = require('next/cache');\n",
        "const cache = require('next/cache'); cache.unstable_cacheLife();\n",
        "const cache = require('next/cache'); cache['unstable_cacheTag']();\n",
        "require('next/cache')['unstable_cacheLife']();\n",
        "import * as cache from 'next/cache'; cache.unstable_cacheTag();\n",
        "const cache = await import('next/cache'); cache.unstable_cacheTag();\n",
        "const { unstable_cacheTag } = await import('next/cache');\n",
        "import('next/cache').then(({ unstable_cacheLife }) => unstable_cacheLife());\n",
        ("import * as cache from 'next/cache';\nconst { unstable_cacheTag } = cache;\n"),
        ("const req = require('next/cache');\nconst { unstable_cacheLife: life } = req;\n"),
        (
            "const promised = import('next/cache');\n"
            "promised.then(({ unstable_cacheTag }) => unstable_cacheTag());\n"
        ),
        "import * as cache from 'next/cache'; cache?.unstable_cacheLife();\n",
    ],
)
def test_next_unstable_cache_residual_covers_pinned_recipe_forms(source: str) -> None:
    assert _next_unstable_cache_residual(source)
    assert not _next_unstable_cache_residual(
        "import { unstable_cache, unstable_noStore } from 'next/cache';\n"
    )


@pytest.mark.parametrize(
    "source",
    [
        "module.exports = { experimental_ppr: true };\n",
        "module.exports = { 'experimental_ppr': true };\n",
        "module.exports = { ['experimental_ppr']: true };\n",
        "const key = 'experimental_ppr'; module.exports = { [key]: true };\n",
        "export const experimental_ppr = true;\n",
    ],
)
def test_next_experimental_ppr_residual_covers_computed_config_keys(source: str) -> None:
    assert _next_experimental_ppr_residual(source)
    assert not _next_experimental_ppr_residual(
        "// experimental_ppr: true\nconst note = 'experimental_ppr';\n"
    )


@pytest.mark.parametrize(
    "source",
    [
        "import('@next/font/google').then(useFont);\n",
        "const font = '@next/font/google'; import(font).then(useFont);\n",
        "const font = '@next/font/local'; require(font);\n",
    ],
)
def test_next_font_residual_covers_dynamic_imports(source: str) -> None:
    assert _next_font_residual(source)
    assert not _next_font_residual("const note = '@next/font/google';\n")


def test_next_unsafe_unwrapped_residual_is_code_aware() -> None:
    assert _next_unsafe_unwrapped_residual(
        "const value = cookies() as unknown as UnsafeUnwrappedCookies;\n"
    )
    assert not _next_unsafe_unwrapped_residual(
        "// UnsafeUnwrappedCookies\nconst note = 'UnsafeUnwrappedDraftMode';\n"
    )


def test_exact_target_and_missing_version_evidence_are_not_fabricated(tmp_path: Path) -> None:
    rust = _repository(tmp_path / "rust-current", _rust_files("2024"))
    assert plan_evolution(rust, ["rust/edition=2024"]).status == "noop"
    downgrade = plan_evolution(rust, ["rust/edition=2021"])
    assert downgrade.status == "blocked"
    assert downgrade.steps[0].status == "failed-precondition"

    react = _repository(
        tmp_path / "react-current",
        {
            "package.json": json.dumps(
                {"dependencies": {"react": "19.3.0", "react-dom": "19.3.0"}}
            ),
            "src/App.jsx": "export default function App() { return null; }\n",
        },
    )
    assert plan_evolution(react, ["react/19-official-codemods=19.3.0"]).status == "blocked"
    (react / "package.json").write_text(json.dumps({"dependencies": {"react": "19.0.0"}}))
    missing = plan_evolution(react, ["react/19-official-codemods=19.3.0"])
    assert missing.status == "blocked"
    assert missing.steps[0].status == "failed-precondition"

    next_marker = _repository(
        tmp_path / "next-current-marker",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": (
                "/* @next-codemod-error Manually await this call. */\n"
                "export default function Page() { return null; }\n"
            ),
        },
    )
    marker_plan = plan_evolution(next_marker, ["next/official-upgrade-codemod=16.3.5"])
    assert marker_plan.status == "ready"
    assert any(
        condition.kind == "no-manual-markers"
        for step in marker_plan.steps
        for condition in step.postconditions
    )


def test_manifest_target_equality_does_not_bypass_semantic_migration_gates(
    tmp_path: Path,
) -> None:
    react = _repository(
        tmp_path / "react-residual",
        {
            "package.json": json.dumps(
                {"dependencies": {"react": "19.3.0", "react-dom": "19.3.0"}}
            ),
            "src/App.jsx": "ReactDOM.render(<App />, document.getElementById('root'));\n",
        },
    )
    react_plan = plan_evolution(react, ["react/19-official-codemods=19.3.0"])
    assert react_plan.status == "blocked"
    assert react_plan.steps[0].operation == "verified-recipe-acquisition"

    next_root = _repository(
        tmp_path / "next-residual",
        {
            "package.json": json.dumps(
                {
                    "scripts": {"lint": "next lint"},
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    },
                }
            ),
            "app/layout.tsx": "export default function Layout() { return null; }\n",
            "middleware.ts": "export function middleware() {}\n",
        },
    )
    next_plan = plan_evolution(next_root, ["next/official-upgrade-codemod=16.3.5"])
    assert next_plan.status == "ready"
    assert any(step.operation == "middleware-to-proxy-16-3-5" for step in next_plan.steps)

    next_15 = _repository(
        tmp_path / "next-15-async",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "15.5.25",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": (
                "import { cookies } from 'next/headers';\n"
                "export default function Page() { return cookies().get('name')?.value; }\n"
            ),
        },
    )
    next_15_plan = plan_evolution(next_15, ["next/official-upgrade-codemod=16.3.5"])
    assert any(step.operation == "next-async-request-api-16-3-5" for step in next_15_plan.steps)
    dependency_step = next(
        step for step in next_15_plan.steps if step.operation == "next-dependencies"
    )
    assert any(
        condition.kind == "no-manual-markers" for condition in dependency_step.postconditions
    )


def test_setup_java_major_is_pinned_without_upgrading_major(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "action",
        {
            ".github/workflows/ci.yml": (
                "name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
                "    steps:\n      - uses: actions/setup-java@v2\n"
            )
        },
    )
    before = project_fingerprint(root)
    plan = plan_evolution(root, ["github-actions/pin-official-actions"])
    dry = apply_evolution(root, plan, dry_run=True, run_blueprint_review=False)
    assert dry.status == "dry_run" and project_fingerprint(root) == before
    result = apply_evolution(root, plan, run_blueprint_review=False)
    expected = OFFICIAL_ACTION_SHAS["actions/setup-java@v2"]
    assert f"actions/setup-java@{expected} # v2" in (root / ".github/workflows/ci.yml").read_text()
    assert "@v4" not in (root / ".github/workflows/ci.yml").read_text()
    repeated = plan_evolution(root, ["github-actions/pin-official-actions"])
    assert repeated.status == "noop"
    rollback = rollback_evolution(root, result.operation_id or "")
    assert rollback.status == "rolled_back" and project_fingerprint(root) == before


def test_stale_target_and_postcondition_failure_restore_exactly(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine
    from blueprint_ai.safety import ProcessResult
    from blueprint_ai.sandbox import Execution, SandboxEvidence

    stale = _repository(tmp_path / "stale", _rust_files("2021"))
    stale_plan = plan_evolution(stale, ["rust/edition=2024"])
    (stale / "Cargo.toml").write_text((stale / "Cargo.toml").read_text() + "# changed\n")
    with pytest.raises(ValueError, match="stale evolution plan"):
        apply_evolution(stale, stale_plan, dry_run=True, run_blueprint_review=False)

    root = _repository(tmp_path / "postcondition", _rust_files("2018"))
    plan = plan_evolution(root, ["rust/edition=2021"])
    before = project_fingerprint(root)

    def fake_execute(command, _execution_root, policy, **_kwargs):
        result = ProcessResult(
            0,
            "cargo 1.98.1\n" if command[-1] == "--version" else "fixed\n",
            "",
            False,
            False,
        )
        evidence = SandboxEvidence(
            backend="host",
            tool="cargo",
            policy=policy,
            teardown=True,
            exit_code=0,
        )
        return Execution(result, evidence)

    monkeypatch.setattr(engine, "execute", fake_execute)
    monkeypatch.setattr(
        engine,
        "_tool_command",
        lambda _root, _tool, _policy, requested=None: requested or "cargo",
    )
    real_postcondition = engine._evaluate_postcondition

    def fail_after_native(workspace, condition):
        if condition.id == "rust/edition-2021":
            from blueprint_ai.evolution.models import EvolutionVerification

            return EvolutionVerification(
                id=condition.id,
                status="failed",
                detail="adversarial postcondition failed after native success",
            )
        return real_postcondition(workspace, condition)

    monkeypatch.setattr(engine, "_evaluate_postcondition", fail_after_native)
    with pytest.raises(RuntimeError, match="postcondition failed after native success"):
        apply_evolution(
            root,
            plan,
            policy=SandboxPolicy(backend="host", trusted=True, writable=True),
            run_blueprint_review=False,
        )
    assert project_fingerprint(root) == before

    failed = apply_evolution(
        root,
        plan,
        policy=SandboxPolicy(backend="host", trusted=True, writable=True),
        run_blueprint_review=False,
        report_failures=True,
    )
    assert failed.status == "failed"
    assert any(
        item.id == "evolution/recovery" and item.status == "passed" for item in failed.verifications
    )


def test_failed_publication_removes_created_gitignored_path(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine
    from blueprint_ai.safety import ProcessResult
    from blueprint_ai.sandbox import Execution, SandboxEvidence

    root = _repository(
        tmp_path / "ignored-publication",
        {
            ".gitignore": "pyproject.toml\n",
            "setup.py": "from setuptools import setup\nsetup(name='demo', version='1')\n",
            "demo.py": "value = 1\n",
        },
    )
    plan = plan_evolution(root, ["python/pep517-build-system=setuptools.build_meta"])

    def fake_execute(command, _execution_root, policy, **_kwargs):
        result = ProcessResult(
            0,
            "Python 3.12.0\n" if command[-1] == "--version" else "built\n",
            "",
            False,
            False,
        )
        evidence = SandboxEvidence(
            backend="host",
            tool="python-build",
            policy=policy,
            teardown=True,
            exit_code=0,
        )
        return Execution(result, evidence)

    monkeypatch.setattr(engine, "execute", fake_execute)
    monkeypatch.setattr(
        engine,
        "_tool_command",
        lambda _root, _tool, _policy, requested=None: requested or "python",
    )
    failed = apply_evolution(
        root,
        plan,
        policy=SandboxPolicy(backend="host", trusted=True, writable=True),
        run_blueprint_review=False,
        report_failures=True,
    )
    assert failed.status == "failed"
    assert not (root / "pyproject.toml").exists()
    assert any(
        item.id == "evolution/recovery" and item.status == "passed" for item in failed.verifications
    )


def test_partial_migration_can_record_explicit_manual_completion(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "accept",
        {
            "Dockerfile": "FROM scratch\nMAINTAINER owner\n",
            "main.tf": 'resource "null_resource" "example" {}\n',
        },
    )
    baseline = project_fingerprint(root)
    plan = plan_evolution(
        root,
        ["container/maintainer-to-oci-label", "iac/terraform-to-opentofu"],
    )
    applied = apply_evolution(root, plan, run_blueprint_review=False)
    assert applied.status == "partial" and applied.operation_id
    (root / "package-lock.json").write_text('{"lockfileVersion": 3}\n')
    with pytest.raises(ValueError, match="sealed completion paths"):
        accept_evolution(
            root,
            applied.operation_id,
            ["terraform plan reviewed against the selected backend and state policy"],
        )
    (root / "package-lock.json").unlink()
    accepted = accept_evolution(
        root,
        applied.operation_id,
        ["terraform plan reviewed against the selected backend and state policy"],
    )
    assert accepted.status == "accepted"
    assert accepted.verifications[0].id == "evolution/manual-acceptance"
    rollback_evolution(root, applied.operation_id)
    assert project_fingerprint(root) == baseline


def test_next_manual_completion_is_sealed_replans_noop_and_rolls_back(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "next-accept",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "15.5.25",
                        "react": "18.3.1",
                        "react-dom": "18.3.1",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    baseline = project_fingerprint(root)
    plan = plan_evolution(root, ["next/official-upgrade-codemod=15.5.25"])
    result = apply_evolution(
        root,
        plan,
        policy=SandboxPolicy(backend="host", trusted=True, writable=True),
        run_blueprint_review=False,
    )
    assert result.status == "partial" and result.operation_id
    (root / "package-lock.json").write_text('{"lockfileVersion": 3}\n')
    accepted = accept_evolution(
        root,
        result.operation_id,
        ["npm install completed", "next build and project tests passed"],
    )
    assert accepted.status == "accepted"
    repeated = plan_evolution(root, ["next/official-upgrade-codemod=15.5.25"])
    assert repeated.status == "noop"
    assert repeated.steps[0].operation == "manual-acceptance-recorded"
    rollback_evolution(root, result.operation_id)
    assert project_fingerprint(root) == baseline


def test_current_next_target_can_start_and_accept_zero_change_verification(
    tmp_path: Path,
) -> None:
    root = _repository(
        tmp_path / "next-current-accept",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    baseline = project_fingerprint(root)
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    assert plan.status == "blocked" and plan.steps[0].operation == "project-verification"
    result = apply_evolution(root, plan, run_blueprint_review=False)
    assert result.status == "partial" and result.operation_id
    (root / "package-lock.json").write_text('{"lockfileVersion": 3}\n')
    accept_evolution(root, result.operation_id, ["next build and project tests passed"])
    repeated = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    assert repeated.status == "noop"
    rollback_evolution(root, result.operation_id)
    assert project_fingerprint(root) == baseline


def test_gitignored_next_lock_is_sealed_and_removed_by_rollback(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "ignored-next-lock",
        {
            ".gitignore": "package-lock.json\n",
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    baseline = project_fingerprint(root)
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    result = apply_evolution(root, plan, run_blueprint_review=False)
    assert result.status == "partial" and result.operation_id
    (root / "package-lock.json").write_text('{"lockfileVersion": 3}\n')
    (root / "yarn.lock").write_text("# generated lock\n")
    with pytest.raises(ValueError, match="exactly one root lockfile"):
        accept_evolution(root, result.operation_id, ["next build and project tests passed"])
    (root / "yarn.lock").unlink()
    accept_evolution(root, result.operation_id, ["next build and project tests passed"])
    assert plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"]).status == "noop"
    rollback_evolution(root, result.operation_id)
    assert not (root / "package-lock.json").exists()
    assert project_fingerprint(root) == baseline


def test_existing_next_lock_can_be_updated_accepted_and_rolled_back(tmp_path: Path) -> None:
    original_lock = "# yarn lockfile v1\nnext@16.3.5:\n"
    root = _repository(
        tmp_path / "existing-next-lock",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "yarn.lock": original_lock,
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    baseline = project_fingerprint(root)
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    result = apply_evolution(root, plan, run_blueprint_review=False)
    assert result.status == "partial" and result.operation_id
    (root / "yarn.lock").write_text(original_lock + "react@19.3.0:\n")
    accepted = accept_evolution(
        root,
        result.operation_id,
        ["yarn install completed", "Next build and tests passed"],
    )
    assert accepted.status == "accepted"
    rollback_evolution(root, result.operation_id)
    assert (root / "yarn.lock").read_text() == original_lock
    assert project_fingerprint(root) == baseline


def test_target_controlled_acceptance_receipt_cannot_bypass_manual_boundary(
    tmp_path: Path,
) -> None:
    root = _repository(
        tmp_path / "forged-acceptance",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    operation_id = "a" * 32
    receipt = root / f".blueprint-ai/operations/{operation_id}.json"
    receipt.parent.mkdir(parents=True)
    receipt.write_text(
        json.dumps(
            {
                "version": 3,
                "kind": "evolution",
                "operation_id": operation_id,
                "status": "accepted",
                "after_fingerprint": project_fingerprint(root),
                "target_versions": {"next/official-upgrade-codemod": "16.3.5"},
                "manual_completion_paths": [],
                "changes": [],
                "manual_acceptance": {
                    "accepted_at": "2026-09-12T00:00:00+00:00",
                    "evidence": ["forged"],
                },
            }
        )
        + "\n"
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    assert plan.status == "blocked"
    assert plan.steps[0].operation == "project-verification"


def test_next_type_only_update_rediscovery_drops_noop_dependency_edit(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "next-types",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "16.3.5",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    },
                    "devDependencies": {
                        "@types/react": "18.3.1",
                        "@types/react-dom": "18.3.1",
                    },
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
        },
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    assert [step.operation for step in plan.steps] == [
        "react-type-dependencies",
        "next-dependencies",
        "project-verification",
    ]
    dependency = plan.steps[1]
    assert dependency.kind == "postcondition" and not dependency.mutates
    dry = apply_evolution(
        root,
        plan,
        dry_run=True,
        policy=SandboxPolicy(backend="host", trusted=True),
        run_blueprint_review=False,
    )
    assert dry.status == "dry_run"


def test_mixed_authoritative_tool_plan_uses_each_sealed_image(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine
    from blueprint_ai.safety import ProcessResult
    from blueprint_ai.sandbox import Execution, SandboxEvidence

    root = _repository(
        tmp_path / "mixed-images",
        {
            "setup.py": "from setuptools import setup\nsetup(name='demo', version='0.1.0')\n",
            **_rust_files("2021"),
        },
    )
    identities = {
        "python-build": "sha256:" + "1" * 64,
        "cargo": "sha256:" + "2" * 64,
    }
    monkeypatch.setattr(engine, "cached_image", lambda tool, _backend: identities.get(tool))
    plan = plan_evolution(
        root,
        [
            "python/pep517-build-system=setuptools.build_meta",
            "rust/edition=2024",
        ],
    )
    seen_images: list[str | None] = []

    def fake_execute(command, _execution_root, policy, *, tool, **_kwargs):
        seen_images.append(policy.image)
        output = (
            "cargo 1.98.1\n"
            if command[-1] == "--version" and tool == "cargo"
            else "Python 3.12.8\n"
            if command[-1] == "--version"
            else "built\n"
        )
        return Execution(
            ProcessResult(0, output, "", False, False),
            SandboxEvidence(
                backend="docker",
                tool=tool,
                policy=policy,
                image_id=identities[tool],
                teardown=True,
                exit_code=0,
            ),
        )

    monkeypatch.setattr(engine, "execute", fake_execute)
    monkeypatch.setattr(
        engine,
        "_tool_command",
        lambda _root, _tool, _policy, requested=None: requested or _tool,
    )
    result = apply_evolution(
        root,
        plan,
        policy=SandboxPolicy(backend="docker", trusted=True, writable=True),
        run_blueprint_review=False,
    )
    assert result.status == "verified"
    assert "blueprint-tools/python-build:3.12-setuptools84" in seen_images
    assert "blueprint-tools/rust:1.98.1-r2" in seen_images


def test_authoritative_contract_cannot_broaden_operator_resource_limits(tmp_path: Path) -> None:
    from blueprint_ai.evolution.engine import _step_policy

    root = _repository(
        tmp_path / "limits",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "15.5.25",
                        "react": "19.3.0",
                        "react-dom": "19.3.0",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return <div />; }\n",
        },
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    codemod = next(step for step in plan.steps if step.kind == "established-codemod")
    operator = SandboxPolicy(
        backend="host",
        trusted=True,
        timeout=1,
        memory_mb=64,
        cpus=0.5,
        pids=16,
        scratch_mb=32,
        file_size_mb=8,
        output_bytes=2048,
    )
    selected = _step_policy(codemod, operator, writable=True)
    assert selected.timeout == 1 and selected.memory_mb == 64 and selected.cpus == 0.5
    assert selected.pids == 16 and selected.scratch_mb == 32
    assert selected.file_size_mb == 8 and selected.output_bytes == 2048
    unrestricted = operator.model_copy(
        update={"network": "unrestricted", "authorize_network": True}
    )
    narrowed = _step_policy(codemod, unrestricted, writable=True)
    assert narrowed.network == "none" and not narrowed.authorize_network


def test_oom_evidence_overrides_nominal_success(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine
    from blueprint_ai.safety import ProcessResult
    from blueprint_ai.sandbox import Execution, SandboxEvidence

    policy = SandboxPolicy(backend="host", trusted=True)

    def fake_execute(command, _root, actual_policy, **_kwargs):
        return Execution(
            ProcessResult(0, "tool said success\n", "", False, False),
            SandboxEvidence(
                backend="docker",
                tool="cargo",
                policy=actual_policy,
                oom_killed=True,
                teardown=True,
                exit_code=0,
            ),
        )

    monkeypatch.setattr(engine, "execute", fake_execute)
    monkeypatch.setattr(
        engine,
        "_tool_command",
        lambda _root, _tool, _policy, requested=None: requested or _tool,
    )
    verification, _output = engine._run(tmp_path, ["cargo", "--version"], policy, {}, tool="cargo")
    assert verification.status == "failed"
    assert "OOM-killed" in verification.detail


def test_read_only_planning_fingerprints_leaf_symlinks(tmp_path: Path) -> None:
    root = _repository(tmp_path / "symlink-plan", {"README.md": "project\n"})
    link = root / ".claude/rules"
    link.parent.mkdir()
    link.symlink_to("../shared-rules")
    _git(root, "add", ".claude/rules")
    _git(root, "commit", "-m", "add bounded link")
    before = project_fingerprint(root)
    plan = plan_evolution(root)
    assert plan.status == "inspection" and plan.metrics["files_in_inventory"] == 2
    link.unlink()
    link.symlink_to("../different-rules")
    assert project_fingerprint(root) != before


def test_go_dependency_pipeline_seals_checksums_vendor_and_offline_test(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "go-dependency",
        {
            "go.mod": "module example.invalid/demo\n\ngo 1.26\n\nrequire example.com/dep v1.2.3\n",
            "main.go": "package demo\n",
        },
    )
    plan = plan_evolution(root, ["go/native-fix"])
    assert [step.operation for step in plan.steps] == [
        "go-module-checksums",
        "go-module-vendor",
        "go-fix",
        "go-test",
    ]
    assert [step.execution_network for step in plan.steps] == [
        "required",
        "required",
        "none",
        "none",
    ]
    assert "-mod=vendor" in plan.steps[2].apply_command
    assert plan.steps[0].files == ["go.sum"]
    assert plan.steps[1].files == [] and plan.steps[1].ephemeral_paths == ["vendor"]
    with pytest.raises(ValueError, match="network authorization"):
        apply_evolution(
            root,
            plan,
            dry_run=True,
            policy=SandboxPolicy(backend="host", trusted=True),
            run_blueprint_review=False,
        )


def test_go_lane_rejects_modules_without_an_explicit_language_version(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "go-no-version",
        {
            "go.mod": "module example.invalid/demo\n\nrequire example.com/dep v1.2.3\n",
            "main.go": "package demo\n",
        },
    )
    assert "go/native-fix" not in plan_evolution(root).candidates


def test_pipeline_stops_on_concurrent_git_index_change(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine

    root = _repository(
        tmp_path / "index-race",
        {
            ".github/workflows/ci.yml": (
                "name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
                "    steps:\n      - uses: actions/setup-java@v2\n"
            )
        },
    )
    plan = plan_evolution(root, ["github-actions/pin-official-actions"])
    before = project_fingerprint(root)
    real_preview = engine._builtin_preview

    def mutate_index(workspace: Path, step):
        blob = _git(root, "rev-parse", "HEAD:.github/workflows/ci.yml")
        _git(root, "update-index", "--cacheinfo", "100755", blob, ".github/workflows/ci.yml")
        return real_preview(workspace, step)

    monkeypatch.setattr(engine, "_builtin_preview", mutate_index)
    with pytest.raises(RuntimeError, match="Git index changed"):
        apply_evolution(root, plan, run_blueprint_review=False)
    assert project_fingerprint(root) == before


def test_each_pipeline_stage_is_confined_to_its_own_scope(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    from blueprint_ai.evolution import engine

    root = _repository(
        tmp_path / "stage-scope",
        {
            "Dockerfile": "FROM scratch\nMAINTAINER owner@example.invalid\n",
            ".github/workflows/ci.yml": (
                "name: ci\non: [push]\njobs:\n  test:\n    runs-on: ubuntu-latest\n"
                "    steps:\n      - uses: actions/setup-java@v2\n"
            ),
        },
    )
    plan = plan_evolution(
        root,
        ["container/maintainer-to-oci-label", "github-actions/pin-official-actions"],
    )
    before = project_fingerprint(root)
    real_preview = engine._builtin_preview

    def cross_stage_write(workspace: Path, step):
        if step.recipe_id == "github-actions/pin-official-actions":
            (workspace / "Dockerfile").write_text("FROM scratch\n# crossed scope\n")
        return real_preview(workspace, step)

    monkeypatch.setattr(engine, "_builtin_preview", cross_stage_write)
    with pytest.raises(RuntimeError, match="crossed its planned scope: Dockerfile"):
        apply_evolution(root, plan, run_blueprint_review=False)
    assert project_fingerprint(root) == before


def test_generated_fixture_and_vendor_surfaces_do_not_establish_applicability(
    tmp_path: Path,
) -> None:
    root = _repository(
        tmp_path / "scopes",
        {
            "fixtures/Cargo.toml": (
                '[package]\nname = "fixture"\nversion = "0.1.0"\nedition = "2018"\n'
            ),
            "fixtures/Cargo.lock": "version = 4\n",
            "fixtures/src/lib.rs": "pub fn fixture() {}\n",
            "vendor/package.json": json.dumps(
                {"dependencies": {"react": "18.3.1", "react-dom": "18.3.1"}}
            ),
            "vendor/src/App.jsx": "export default function App() { return null; }\n",
        },
    )
    plan = plan_evolution(root)
    assert "rust/edition" not in plan.candidates
    assert "react/19-official-codemods" not in plan.candidates


def test_next_lane_is_scoped_to_the_root_component(tmp_path: Path) -> None:
    root = _repository(
        tmp_path / "next-components",
        {
            "package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "15.5.25",
                        "react": "18.3.1",
                        "react-dom": "18.3.1",
                    }
                }
            ),
            "app/page.tsx": "export default function Page() { return null; }\n",
            "child/package.json": json.dumps(
                {
                    "dependencies": {
                        "next": "14.2.0",
                        "react": "18.3.1",
                        "react-dom": "18.3.1",
                    }
                }
            ),
            "child/app/cache.ts": (
                "import { unstable_cacheTag } from 'next/cache';\n"
                "export const tag = unstable_cacheTag;\n"
            ),
        },
    )
    plan = plan_evolution(root, ["next/official-upgrade-codemod=16.3.5"])
    assert plan.current_state.versions["npm:next"] == "15.5.25"
    assert plan.current_state.versions["npm:next@child"] == "14.2.0"
    assert "next/official-upgrade-codemod" not in plan.candidates
    assert plan.status == "blocked" and plan.steps[0].status == "failed-precondition"
