from __future__ import annotations

import hashlib
import json
import os
import shutil
import uuid
from datetime import UTC, datetime
from pathlib import Path

from pydantic import BaseModel, Field

from blueprint_ai.core import Finding, ProjectFacts
from blueprint_ai.safety import (
    MAX_MANIFEST_BYTES,
    atomic_write_text,
    read_text_bounded,
    run_process,
)

TEMPLATES = {
    ".editorconfig": """root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
""",
    ".pre-commit-config.yaml": """repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
""",
}


class CapabilityKit(BaseModel):
    name: str
    version: int = 1
    profiles: list[str] = Field(default_factory=list)
    files: dict[str, str]
    verification: list[list[str]] = Field(default_factory=list)


KITS: dict[str, CapabilityKit] = {
    "testing-python": CapabilityKit(
        name="testing-python",
        profiles=["library", "cli", "api", "backend-service", "ai-app"],
        files={
            "tests/test_blueprint_generated_smoke.py": '''"""Generated by Blueprint AI."""

from pathlib import Path


def test_project_manifest_exists() -> None:
    assert (Path(__file__).parents[1] / "pyproject.toml").is_file()
'''
        },
        verification=[["pytest", "-q", "tests/test_blueprint_generated_smoke.py"]],
    ),
    "testing-javascript": CapabilityKit(
        name="testing-javascript",
        profiles=["frontend", "web-app", "full-stack", "cli"],
        files={
            "tests/blueprint.generated.smoke.test.cjs": """// Generated by Blueprint AI.
const assert = require("node:assert/strict");
const test = require("node:test");

test("package manifest exists", () => assert.ok(require("../package.json").name));
"""
        },
        verification=[["node", "--test", "tests/blueprint.generated.smoke.test.cjs"]],
    ),
    "pre-commit": CapabilityKit(
        name="pre-commit",
        profiles=["library", "cli", "api", "web-app", "open-source", "production"],
        files={".pre-commit-config.yaml": TEMPLATES[".pre-commit-config.yaml"]},
        verification=[["pre-commit", "run", "--all-files"]],
    ),
    "github-actions-ci": CapabilityKit(
        name="github-actions-ci",
        profiles=["open-source", "production"],
        files={
            ".github/workflows/ci.yml": """name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: test -f README.md || test -f pyproject.toml || test -f package.json
"""
        },
    ),
    "terraform": CapabilityKit(
        name="terraform",
        profiles=["iac", "terraform", "production"],
        files={
            ".tflint.hcl": 'plugin "terraform" {\n  enabled = true\n  preset = "recommended"\n}\n'
        },
        verification=[["terraform", "fmt", "-check", "-recursive"], ["terraform", "validate"]],
    ),
    "container": CapabilityKit(
        name="container",
        profiles=["container", "kubernetes", "production"],
        files={".dockerignore": ".git\n.blueprint-ai\n.env*\nnode_modules\n.venv\n"},
    ),
    "api-contract": CapabilityKit(
        name="api-contract",
        profiles=["api", "backend-service", "full-stack"],
        files={".spectral.yaml": "extends: [spectral:oas, spectral:asyncapi]\n"},
        verification=[["spectral", "lint", "--format", "json", "openapi.yaml"]],
    ),
    "observability": CapabilityKit(
        name="observability",
        profiles=["api", "backend-service", "data-pipeline", "production"],
        files={
            "docs/observability.md": """# Observability

Document owned logs, metrics, traces, correlation identifiers, health signals, alerts,
dashboards, retention, and the verification command for this service.
"""
        },
    ),
    "oss-repository": CapabilityKit(
        name="oss-repository",
        profiles=["open-source"],
        files={
            "SECURITY.md": (
                "# Security\n\nDocument supported versions and a private reporting channel.\n"
            ),
            "CONTRIBUTING.md": (
                "# Contributing\n\nDocument setup, checks, review, and release expectations.\n"
            ),
        },
    ),
    "ai-context": CapabilityKit(
        name="ai-context",
        profiles=["ai-app", "ai-agent"],
        files={
            "docs/ai-context.md": """# AI context contract

Record provider/model versions, structured outputs, tool permissions, untrusted-input
boundaries, eval datasets, token/cost budgets, caching, and reproducibility settings.
"""
        },
    ),
}


class Change(BaseModel):
    target: str
    status: str
    blueprint: str
    detail: str
    sha256: str | None = None


class Verification(BaseModel):
    command: list[str]
    status: str
    detail: str


class ApplyResult(BaseModel):
    operation_id: str | None = None
    manifest_path: str | None = None
    changes: list[Change] = Field(default_factory=list)
    verifications: list[Verification] = Field(default_factory=list)

    @property
    def changed(self) -> list[Change]:
        return [change for change in self.changes if change.status == "changed"]


def _readme(facts: ProjectFacts) -> str:
    return f"""# {facts.name}

{facts.name} project.

## Install

Use the package manager declared by the project.

## Usage

See the source entry points for current usage.
"""


def _test_scaffold(root: Path, target: str) -> str:
    if target.endswith(".py"):
        packages = []
        source = root / "src"
        if source.is_dir():
            packages = [
                path.name
                for path in source.iterdir()
                if path.is_dir() and (path / "__init__.py").is_file()
            ]
        if packages:
            return f'''"""Generated by Blueprint AI; replace with behavior assertions."""

from pathlib import Path


def test_package_layout() -> None:
    package = Path(__file__).parents[1] / "src" / {packages[0]!r}
    assert (package / "__init__.py").is_file()
'''
        return '''"""Generated by Blueprint AI; replace with behavior assertions."""

from pathlib import Path


def test_project_manifest_exists() -> None:
    assert (Path(__file__).parents[1] / "pyproject.toml").is_file()
'''
    module = False
    package_json = root / "package.json"
    if package_json.is_file():
        try:
            module = json.loads(package_json.read_text(encoding="utf-8")).get("type") == "module"
        except ValueError:
            pass
    if module:
        return """// Generated by Blueprint AI; replace with behavior assertions.
import assert from "node:assert/strict";
import test from "node:test";

test("project smoke", () => assert.ok(true));
"""
    return """// Generated by Blueprint AI; replace with behavior assertions.
const assert = require("node:assert/strict");
const test = require("node:test");

test("project smoke", () => assert.ok(true));
"""


def _safe_target(root: Path, value: str) -> Path | None:
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts:
        return None
    target = (root / relative).resolve()
    try:
        target.relative_to(root.resolve())
    except ValueError:
        return None
    current = root.resolve()
    for part in relative.parts[:-1]:
        current = current / part
        if current.is_symlink():
            return None
    return target


def _atomic_create(root: Path, target: Path, content: str) -> str:
    return atomic_write_text(target, content, overwrite=False, root=root)


def _content_for(root: Path, facts: ProjectFacts, kind: str, target: str) -> str | None:
    if kind == "template" and target in TEMPLATES:
        return TEMPLATES[target]
    if kind == "template" and target == "README.md":
        return _readme(facts)
    if kind == "test-scaffold":
        return _test_scaffold(root, target)
    return None


def _record_manifest(root: Path, result: ApplyResult) -> None:
    if not result.changed or not result.operation_id:
        return
    relative = Path(".blueprint-ai") / "operations" / f"{result.operation_id}.json"
    target = _operation_manifest_target(root, result.operation_id)
    payload = {
        "version": 1,
        "operation_id": result.operation_id,
        "created_at": datetime.now(UTC).isoformat(),
        "changes": [change.model_dump(mode="json") for change in result.changed],
    }
    _atomic_create(root, target, json.dumps(payload, indent=2) + "\n")
    result.manifest_path = relative.as_posix()


def _operation_manifest_target(root: Path, operation_id: str) -> Path:
    relative = Path(".blueprint-ai") / "operations" / f"{operation_id}.json"
    target = _safe_target(root, relative.as_posix())
    if target is None:
        raise OSError("operation manifest path crosses a symlink boundary")
    return target


def _commit_manifest_or_rollback(root: Path, result: ApplyResult) -> None:
    try:
        _record_manifest(root, result)
    except OSError:
        for change in result.changed:
            target = _safe_target(root, change.target)
            if target and target.is_file() and not target.is_symlink():
                if hashlib.sha256(target.read_bytes()).hexdigest() == change.sha256:
                    target.unlink()
                    change.status = "rolled_back"
                    change.detail = "write rolled back because the operation manifest failed"
        raise


def _verify_kit(root: Path, kit: CapabilityKit, result: ApplyResult) -> None:
    for command in kit.verification:
        executable = shutil.which(command[0])
        if not executable:
            result.verifications.append(
                Verification(
                    command=command,
                    status="tool_missing",
                    detail=f"{command[0]} is not installed",
                )
            )
            continue
        try:
            completed = run_process([executable, *command[1:]], root, 120)
        except OSError as exc:
            result.verifications.append(
                Verification(command=command, status="tool_error", detail=str(exc)[:500])
            )
            continue
        detail = (completed.stdout + "\n" + completed.stderr).strip()[-500:]
        result.verifications.append(
            Verification(
                command=command,
                status="passed" if completed.returncode == 0 else "failed",
                detail=detail or f"exit {completed.returncode}",
            )
        )


def _apply_files(
    root: Path,
    result: ApplyResult,
    blueprint: str,
    files: dict[str, str],
    detail: str,
) -> None:
    planned: list[tuple[str, Path, str]] = []
    conflict = False
    for relative, content in files.items():
        target = _safe_target(root, relative)
        if target is None:
            conflict = True
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=blueprint,
                    detail="target or parent symlink escapes the project safety boundary",
                )
            )
        elif os.path.lexists(target):
            result.changes.append(
                Change(
                    target=relative,
                    status="skipped",
                    blueprint=blueprint,
                    detail="existing path preserved",
                )
            )
        else:
            planned.append((relative, target, content))
    if conflict:
        for relative, _target, _content in planned:
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=blueprint,
                    detail="transaction aborted during preflight",
                )
            )
        return
    created: list[Path] = []
    try:
        for relative, target, content in planned:
            digest = _atomic_create(root, target, content)
            created.append(target)
            result.changes.append(
                Change(
                    target=relative,
                    status="changed",
                    blueprint=blueprint,
                    detail=detail,
                    sha256=digest,
                )
            )
    except OSError as exc:
        for target in reversed(created):
            target.unlink(missing_ok=True)
        created_targets = {target.relative_to(root).as_posix() for target in created}
        for change in result.changes:
            if change.status == "changed" and change.target in created_targets:
                change.status = "rolled_back"
                change.detail = "transaction rolled back after a later write conflict"
        result.changes.append(
            Change(
                target=relative,
                status="conflicted",
                blueprint=blueprint,
                detail=f"transaction rolled back after write conflict: {str(exc)[:200]}",
            )
        )


def apply_kit(root: Path, facts: ProjectFacts, name: str) -> ApplyResult:
    try:
        kit = KITS[name]
    except KeyError as exc:
        raise ValueError(f"unknown capability kit: {name}") from exc
    operation_id = uuid.uuid4().hex
    result = ApplyResult(operation_id=operation_id)
    required_language = {
        "testing-python": "Python",
        "testing-javascript": "JavaScript",
    }.get(name)
    if (
        required_language
        and required_language not in facts.languages
        and not (name == "testing-javascript" and "TypeScript" in facts.languages)
    ):
        result.operation_id = None
        result.changes.append(
            Change(
                target=name,
                status="unsupported",
                blueprint=f"kit:{name}",
                detail=f"{required_language} project evidence was not discovered",
            )
        )
        return result
    _operation_manifest_target(root, operation_id)
    _apply_files(root, result, f"kit:{name}", kit.files, f"apply {name} kit v{kit.version}")
    if result.changed:
        _verify_kit(root, kit, result)
    _commit_manifest_or_rollback(root, result)
    if not result.changed:
        result.operation_id = None
    return result


def apply_findings(root: Path, facts: ProjectFacts, findings: list[Finding]) -> ApplyResult:
    operation_id = uuid.uuid4().hex
    result = ApplyResult(operation_id=operation_id)
    _operation_manifest_target(root, operation_id)
    seen: set[str] = set()
    for finding in findings:
        remediation = finding.remediation
        if (
            not remediation
            or not remediation.safe
            or remediation.target in seen
            or finding.provenance != "deterministic"
            or finding.source != "blueprint-ai"
            or finding.disposition != "new"
        ):
            continue
        seen.add(remediation.target)
        if remediation.kind == "kit":
            kit = KITS.get(remediation.target)
            if not kit:
                result.changes.append(
                    Change(
                        target=remediation.target,
                        status="conflicted",
                        blueprint=finding.blueprint,
                        detail="unsupported capability kit",
                    )
                )
                continue
            _apply_files(root, result, finding.blueprint, kit.files, remediation.description)
            continue
        content = _content_for(root, facts, remediation.kind, remediation.target)
        if content is None:
            result.changes.append(
                Change(
                    target=remediation.target,
                    status="conflicted",
                    blueprint=finding.blueprint,
                    detail="unsupported remediation",
                )
            )
            continue
        _apply_files(
            root,
            result,
            finding.blueprint,
            {remediation.target: content},
            remediation.description,
        )
    _commit_manifest_or_rollback(root, result)
    if not result.changed:
        result.operation_id = None
    return result


def rollback_operation(root: Path, operation_id: str) -> ApplyResult:
    if not __import__("re").fullmatch(r"[0-9a-f]{32}", operation_id):
        raise ValueError("invalid operation id")
    manifest = root / ".blueprint-ai" / "operations" / f"{operation_id}.json"
    if not manifest.is_file():
        raise ValueError(f"unknown operation: {operation_id}")
    try:
        data = json.loads(read_text_bounded(manifest, MAX_MANIFEST_BYTES, root=root))
    except (OSError, ValueError, UnicodeError) as exc:
        raise ValueError(f"invalid operation manifest: {exc}") from exc
    if data.get("version") != 1 or data.get("operation_id") != operation_id:
        raise ValueError("operation manifest identity or version does not match")
    result = ApplyResult(
        operation_id=operation_id, manifest_path=manifest.relative_to(root).as_posix()
    )
    for row in reversed(data.get("changes", [])):
        relative = str(row.get("target", ""))
        target = _safe_target(root, relative)
        if target is None or target.is_symlink() or not target.is_file():
            result.changes.append(
                Change(
                    target=relative,
                    status="skipped",
                    blueprint=str(row.get("blueprint", "rollback")),
                    detail="created file is already absent",
                )
            )
            continue
        digest = hashlib.sha256(target.read_bytes()).hexdigest()
        if digest != row.get("sha256"):
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=str(row.get("blueprint", "rollback")),
                    detail="file changed after apply; preserved",
                )
            )
            continue
        target.unlink()
        result.changes.append(
            Change(
                target=relative,
                status="rolled_back",
                blueprint=str(row.get("blueprint", "rollback")),
                detail="removed unchanged file created by operation",
            )
        )
    return result
