from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

from pydantic import BaseModel, Field

from blueprint_ai.core import Finding, ProjectFacts
from blueprint_ai.safety import (
    MAX_MANIFEST_BYTES,
    atomic_write_text,
    read_bytes_bounded,
    read_text_bounded,
)

if TYPE_CHECKING:
    from blueprint_ai.evolution.models import EvolutionReport

TEMPLATES = {
    ".editorconfig": """root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.md]
trim_trailing_whitespace = false
""",
    ".pre-commit-config.yaml": """repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
""",
}


class CapabilityKit(BaseModel):
    name: str
    version: int = 1
    profiles: list[str] = Field(default_factory=list)
    files: dict[str, str]
    verification: list[list[str]] = Field(default_factory=list)
    alternative_files: list[str] = Field(default_factory=list)
    alternative_json_sections: dict[str, str] = Field(default_factory=dict)


KITS: dict[str, CapabilityKit] = {
    "testing-python": CapabilityKit(
        name="testing-python",
        profiles=["library", "cli", "api", "backend-service", "ai-app"],
        files={
            "tests/test_blueprint_generated_smoke.py": '''"""Generated by Blueprint AI."""

from pathlib import Path


def test_project_manifest_exists() -> None:
    assert (Path(__file__).parents[1] / "pyproject.toml").is_file()
'''
        },
        verification=[["pytest", "-q", "tests/test_blueprint_generated_smoke.py"]],
    ),
    "testing-javascript": CapabilityKit(
        name="testing-javascript",
        profiles=["frontend", "web-app", "full-stack", "cli"],
        files={
            "tests/blueprint.generated.smoke.test.cjs": """// Generated by Blueprint AI.
const assert = require("node:assert/strict");
const test = require("node:test");

test("package manifest exists", () => assert.ok(require("../package.json").name));
"""
        },
        verification=[["node", "--test", "tests/blueprint.generated.smoke.test.cjs"]],
    ),
    "pre-commit": CapabilityKit(
        name="pre-commit",
        profiles=["library", "cli", "api", "web-app", "open-source", "production"],
        files={".pre-commit-config.yaml": TEMPLATES[".pre-commit-config.yaml"]},
        verification=[["pre-commit", "run", "--all-files"]],
    ),
    "github-actions-ci": CapabilityKit(
        name="github-actions-ci",
        profiles=["open-source", "production"],
        files={
            ".github/workflows/ci.yml": """name: CI
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - run: test -f README.md || test -f pyproject.toml || test -f package.json
"""
        },
    ),
    "terraform": CapabilityKit(
        name="terraform",
        profiles=["iac", "terraform", "production"],
        files={
            ".tflint.hcl": 'plugin "terraform" {\n  enabled = true\n  preset = "recommended"\n}\n'
        },
        verification=[["terraform", "fmt", "-check", "-recursive"], ["terraform", "validate"]],
    ),
    "container": CapabilityKit(
        name="container",
        profiles=["container", "kubernetes", "production"],
        files={".dockerignore": ".git\n.blueprint-ai\n.env*\nnode_modules\n.venv\n"},
    ),
    "api-contract": CapabilityKit(
        name="api-contract",
        profiles=["api", "backend-service", "full-stack"],
        files={".spectral.yaml": "extends: [spectral:oas, spectral:asyncapi]\n"},
        verification=[["spectral", "lint", "--format", "json", "openapi.yaml"]],
    ),
    "observability": CapabilityKit(
        name="observability",
        profiles=["api", "backend-service", "data-pipeline", "production"],
        files={
            "docs/observability.md": """# Observability

Document owned logs, metrics, traces, correlation identifiers, health signals, alerts,
dashboards, retention, and the verification command for this service.
"""
        },
    ),
    "oss-repository": CapabilityKit(
        name="oss-repository",
        profiles=["open-source"],
        files={
            "SECURITY.md": (
                "# Security\n\nDocument supported versions and a private reporting channel.\n"
            ),
            "CONTRIBUTING.md": (
                "# Contributing\n\nDocument setup, checks, review, and release expectations.\n"
            ),
        },
    ),
    "ai-context": CapabilityKit(
        name="ai-context",
        profiles=["ai-app", "ai-agent"],
        files={
            "docs/ai-context.md": """# AI context contract

Record provider/model versions, structured outputs, tool permissions, untrusted-input
boundaries, eval datasets, token/cost budgets, caching, and reproducibility settings.
"""
        },
    ),
}


# Small declarative kits; activation of services/accounts remains outside a local file mutation.
KITS.update(
    {
        "security-policy": CapabilityKit(
            name="security-policy",
            files={
                "SECURITY.md": (
                    "# Security\n\nDocument supported versions and the private vuln"
                    "erability reporting channel before publication.\n"
                )
            },
        ),
        "dependency-updates": CapabilityKit(
            name="dependency-updates",
            files={"renovate.json": '{"extends": ["config:recommended"]}\n'},
            alternative_files=[
                *[
                    prefix + "renovate." + extension
                    for prefix in ("", ".github/", ".gitlab/")
                    for extension in ("json", "jsonc", "json5")
                    if prefix or extension != "json"
                ],
                ".renovaterc",
                ".renovaterc.json",
                ".renovaterc.jsonc",
                ".renovaterc.json5",
            ],
            alternative_json_sections={"package.json": "renovate"},
        ),
        "secret-scanning": CapabilityKit(
            name="secret-scanning", files={".gitleaks.toml": "[extend]\nuseDefault = true\n"}
        ),
        "sast": CapabilityKit(
            name="sast",
            alternative_files=[".semgrep.yaml"],
            files={
                ".semgrep.yml": (
                    "rules:\n  - id: unsafe-eval\n    languages: [python]\n    sever"
                    "ity: ERROR\n    message: Review evaluation of dynamic code.\n "
                    "   pattern: eval(...)\n"
                )
            },
        ),
        "devcontainer": CapabilityKit(
            name="devcontainer",
            alternative_files=[".devcontainer.json"],
            files={
                ".devcontainer/devcontainer.json": (
                    '{"name":"Project workspace","image":"mcr.microsoft.com/devco'
                    'ntainers/base:ubuntu","remoteUser":"vscode"}\n'
                )
            },
        ),
        "release-checklist": CapabilityKit(
            name="release-checklist",
            files={
                "docs/releasing.md": (
                    "# Releasing\n\n1. Review the version and changelog.\n2. Run the"
                    " native build and tests from a clean checkout.\n3. Audit depe"
                    "ndencies and inspect package contents.\n4. Test a fresh isola"
                    "ted installation.\n5. Review the artifact digest and publishe"
                    "r identity.\n6. Publish only with explicit release authorizat"
                    "ion.\n"
                )
            },
        ),
    }
)


class Change(BaseModel):
    target: str
    status: str
    blueprint: str
    detail: str
    sha256: str | None = None


class Verification(BaseModel):
    command: list[str]
    status: str
    detail: str
    sandbox: dict | None = None


class ApplyResult(BaseModel):
    operation_id: str | None = None
    manifest_path: str | None = None
    changes: list[Change] = Field(default_factory=list)
    verifications: list[Verification] = Field(default_factory=list)
    created_directories: list[str] = Field(default_factory=list)

    @property
    def changed(self) -> list[Change]:
        return [change for change in self.changes if change.status == "changed"]


def _readme(facts: ProjectFacts) -> str:
    return f"""# {facts.name}

{facts.name} project.

## Install

Use the package manager declared by the project.

## Usage

See the source entry points for current usage.
"""


def _test_scaffold(root: Path, target: str) -> str | None:
    if target.endswith(".py"):
        packages = []
        source = root / "src"
        if source.is_symlink():
            return None
        if source.is_dir():
            packages = [
                path.name
                for path in source.iterdir()
                if not path.is_symlink()
                and path.is_dir()
                and not (path / "__init__.py").is_symlink()
                and (path / "__init__.py").is_file()
            ]
        if packages:
            return f'''"""Generated by Blueprint AI; replace with behavior assertions."""

from pathlib import Path


def test_package_layout() -> None:
    package = Path(__file__).parents[1] / "src" / {packages[0]!r}
    assert (package / "__init__.py").is_file()
'''
        return '''"""Generated by Blueprint AI; replace with behavior assertions."""

from pathlib import Path


def test_project_manifest_exists() -> None:
    assert (Path(__file__).parents[1] / "pyproject.toml").is_file()
'''
    module = False
    package_json = root / "package.json"
    if os.path.lexists(package_json):
        try:
            package = json.loads(read_text_bounded(package_json, MAX_MANIFEST_BYTES, root=root))
        except (OSError, ValueError, UnicodeError):
            return None
        if not isinstance(package, dict):
            return None
        module = package.get("type") == "module"
    if module:
        return """// Generated by Blueprint AI; replace with behavior assertions.
import assert from "node:assert/strict";
import test from "node:test";

test("project smoke", () => assert.ok(true));
"""
    return """// Generated by Blueprint AI; replace with behavior assertions.
const assert = require("node:assert/strict");
const test = require("node:test");

test("project smoke", () => assert.ok(true));
"""


def _safe_target(root: Path, value: str) -> Path | None:
    relative = Path(value)
    if relative.is_absolute() or ".." in relative.parts:
        return None
    current = root.resolve()
    for part in relative.parts:
        current = current / part
        if current.is_symlink():
            return None
    target = current.resolve()
    try:
        target.relative_to(root.resolve())
    except ValueError:
        return None
    return target


def _kit_configuration_conflicts(root: Path, kit: CapabilityKit) -> list[str]:
    conflicts = []
    for relative in kit.alternative_files:
        target = _safe_target(root, relative)
        if target is None or os.path.lexists(target):
            conflicts.append(relative)
    for relative, section in kit.alternative_json_sections.items():
        target = _safe_target(root, relative)
        if target is None:
            conflicts.append(relative)
        elif os.path.lexists(target):
            try:
                content = json.loads(read_text_bounded(target, MAX_MANIFEST_BYTES, root=root))
                if not isinstance(content, dict) or section in content:
                    conflicts.append(relative + "#" + section)
            except (OSError, ValueError, UnicodeError):
                conflicts.append(relative)
    return conflicts


def _atomic_create(root: Path, target: Path, content: str) -> str:
    return atomic_write_text(target, content, overwrite=False, root=root)


def _content_for(root: Path, facts: ProjectFacts, kind: str, target: str) -> str | None:
    if kind == "template" and target in TEMPLATES:
        return TEMPLATES[target]
    if kind == "template" and target == "README.md":
        return _readme(facts)
    if kind == "test-scaffold":
        return _test_scaffold(root, target)
    return None


def _remember_directories(root: Path, target: Path, result: ApplyResult) -> None:
    for parent in reversed(target.parents):
        if parent != root and parent.is_relative_to(root) and not parent.exists():
            relative = parent.relative_to(root).as_posix()
            if relative not in result.created_directories:
                result.created_directories.append(relative)


def _remove_empty_created_directories(root: Path, directories: list[str]) -> None:
    for relative in sorted(directories, key=lambda p: len(Path(p).parts), reverse=True):
        target = _safe_target(root, relative)
        if target and target != root and not target.is_symlink():
            try:
                target.rmdir()
            except OSError:
                pass


def _record_manifest(root: Path, result: ApplyResult) -> None:
    if not result.changed or not result.operation_id:
        return
    relative = Path(".blueprint-ai") / "operations" / f"{result.operation_id}.json"
    target = _operation_manifest_target(root, result.operation_id)
    _remember_directories(root, target, result)
    payload = {
        "version": 2,
        "created_directories": result.created_directories,
        "operation_id": result.operation_id,
        "created_at": datetime.now(UTC).isoformat(),
        "changes": [change.model_dump(mode="json") for change in result.changed],
    }
    _atomic_create(root, target, json.dumps(payload, indent=2) + "\n")
    result.manifest_path = relative.as_posix()


def _operation_manifest_target(root: Path, operation_id: str) -> Path:
    relative = Path(".blueprint-ai") / "operations" / f"{operation_id}.json"
    target = _safe_target(root, relative.as_posix())
    if target is None:
        raise OSError("operation manifest path crosses a symlink boundary")
    return target


def _commit_manifest_or_rollback(root: Path, result: ApplyResult) -> None:
    try:
        _record_manifest(root, result)
    except OSError:
        _rollback_created_changes(root, result, "operation manifest failed")
        _remove_empty_created_directories(root, result.created_directories)
        raise


def _matches_created_file(root: Path, target: Path, digest: str | None) -> bool:
    try:
        return (
            hashlib.sha256(read_bytes_bounded(target, MAX_MANIFEST_BYTES, root=root)).hexdigest()
            == digest
        )
    except (OSError, ValueError):
        return False


def _rollback_created_changes(root: Path, result: ApplyResult, reason: str) -> None:
    for change in result.changed:
        target = _safe_target(root, change.target)
        if target and _matches_created_file(root, target, change.sha256):
            target.unlink()
            change.status = "rolled_back"
            change.detail = "transaction rolled back: " + reason
        else:
            change.status = "conflicted"
            change.detail = "file changed during transaction; preserved after " + reason


def _verify_kit(root: Path, kit: CapabilityKit, result: ApplyResult, sandbox=None) -> None:
    import ast
    import tomllib

    import yaml

    from blueprint_ai.sandbox import SandboxPolicy, SandboxUnavailable, execute

    # Verify the bytes that were created, before any optional project-controlled verifier.
    try:
        for relative in (change.target for change in result.changed):
            content = read_text_bounded(root / relative, MAX_MANIFEST_BYTES, root=root)
            extension = Path(relative).suffix
            if extension == ".json":
                json.loads(content)
            elif extension in {".yaml", ".yml"}:
                yaml.safe_load(content)
            elif extension == ".toml":
                tomllib.loads(content)
            elif extension == ".py":
                ast.parse(content)
            if not content.strip():
                raise ValueError("empty generated asset")
    except (OSError, ValueError, SyntaxError, yaml.YAMLError) as exc:
        result.verifications.append(
            Verification(
                command=["builtin:validate-assets"], status="failed", detail=str(exc)[:500]
            )
        )
        return
    result.verifications.append(
        Verification(
            command=["builtin:validate-assets"],
            status="passed",
            detail="Created text is readable; JSON/YAML/TOML/Python assets parse successfully",
        )
    )
    policy = sandbox or SandboxPolicy()
    for command in kit.verification:
        executable = shutil.which(command[0])
        if not executable and policy.trusted and policy.backend in {"auto", "host"}:
            result.verifications.append(
                Verification(
                    command=command,
                    status="tool_missing",
                    detail=f"{command[0]} is not installed",
                )
            )
            continue
        try:
            execution = execute(
                command,
                root,
                policy,
                tool=command[0],
            )
            completed = execution.result
        except (OSError, SandboxUnavailable) as exc:
            result.verifications.append(
                Verification(command=command, status="tool_error", detail=str(exc)[:500])
            )
            continue
        detail = (completed.stdout + "\n" + completed.stderr).strip()[-500:]
        okay = (
            completed.returncode == 0 and not completed.timed_out and not completed.output_truncated
        )
        if completed.timed_out:
            detail = "verifier timed out; " + detail
        elif completed.output_truncated:
            detail = "verifier output was truncated; " + detail
        result.verifications.append(
            Verification(
                command=command,
                status="passed" if okay else "failed",
                detail=detail or f"exit {completed.returncode}",
                sandbox=execution.evidence.model_dump(mode="json"),
            )
        )


def _apply_files(
    root: Path,
    result: ApplyResult,
    blueprint: str,
    files: dict[str, str],
    detail: str,
    existing_configuration: list[str] | None = None,
) -> None:
    planned: list[tuple[str, Path, str]] = []
    conflict = bool(existing_configuration)
    for relative in existing_configuration or []:
        result.changes.append(
            Change(
                target=relative,
                status="conflicted",
                blueprint=blueprint,
                detail="equivalent existing configuration preserved; no duplicate asset created",
            )
        )
    for relative, content in files.items():
        target = _safe_target(root, relative)
        if target is None:
            conflict = True
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=blueprint,
                    detail="target or parent symlink escapes the project safety boundary",
                )
            )
        elif os.path.lexists(target):
            result.changes.append(
                Change(
                    target=relative,
                    status="skipped",
                    blueprint=blueprint,
                    detail="existing path preserved",
                )
            )
        else:
            planned.append((relative, target, content))
    if conflict:
        for relative, _target, _content in planned:
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=blueprint,
                    detail="transaction aborted during preflight",
                )
            )
        return
    try:
        for relative, target, content in planned:
            _remember_directories(root, target, result)
            digest = _atomic_create(root, target, content)
            result.changes.append(
                Change(
                    target=relative,
                    status="changed",
                    blueprint=blueprint,
                    detail=detail,
                    sha256=digest,
                )
            )
    except OSError as exc:
        _rollback_created_changes(root, result, "a later write conflict")
        _remove_empty_created_directories(root, result.created_directories)
        result.changes.append(
            Change(
                target=relative,
                status="conflicted",
                blueprint=blueprint,
                detail=f"transaction rolled back after write conflict: {str(exc)[:200]}",
            )
        )


def apply_kit(root: Path, facts: ProjectFacts, name: str, *, sandbox=None) -> ApplyResult:
    try:
        kit = KITS[name]
    except KeyError as exc:
        raise ValueError(f"unknown capability kit: {name}") from exc
    operation_id = uuid.uuid4().hex
    result = ApplyResult(operation_id=operation_id)
    required_language = {
        "testing-python": "Python",
        "testing-javascript": "JavaScript",
    }.get(name)
    if (
        required_language
        and required_language not in facts.languages
        and not (name == "testing-javascript" and "TypeScript" in facts.languages)
    ):
        result.operation_id = None
        result.changes.append(
            Change(
                target=name,
                status="unsupported",
                blueprint=f"kit:{name}",
                detail=f"{required_language} project evidence was not discovered",
            )
        )
        return result
    _operation_manifest_target(root, operation_id)
    _apply_files(
        root,
        result,
        f"kit:{name}",
        kit.files,
        f"apply {name} kit v{kit.version}",
        _kit_configuration_conflicts(root, kit),
    )
    if result.changed:
        _verify_kit(root, kit, result, sandbox=sandbox)
        if any(v.status == "failed" for v in result.verifications):
            _rollback_created_changes(root, result, "capability verification failed")
            _remove_empty_created_directories(root, result.created_directories)
    _commit_manifest_or_rollback(root, result)
    if not result.changed:
        result.operation_id = None
    return result


def apply_findings(root: Path, facts: ProjectFacts, findings: list[Finding]) -> ApplyResult:
    operation_id = uuid.uuid4().hex
    result = ApplyResult(operation_id=operation_id)
    _operation_manifest_target(root, operation_id)
    seen: set[str] = set()
    for finding in findings:
        remediation = finding.remediation
        if (
            not remediation
            or not remediation.safe
            or remediation.target in seen
            or finding.provenance != "deterministic"
            or finding.source != "blueprint-ai"
            or finding.disposition != "new"
        ):
            continue
        seen.add(remediation.target)
        if remediation.kind == "kit":
            kit = KITS.get(remediation.target)
            if not kit:
                result.changes.append(
                    Change(
                        target=remediation.target,
                        status="conflicted",
                        blueprint=finding.blueprint,
                        detail="unsupported capability kit",
                    )
                )
                continue
            _apply_files(
                root,
                result,
                finding.blueprint,
                kit.files,
                remediation.description,
                _kit_configuration_conflicts(root, kit),
            )
            continue
        content = _content_for(root, facts, remediation.kind, remediation.target)
        if content is None:
            result.changes.append(
                Change(
                    target=remediation.target,
                    status="conflicted",
                    blueprint=finding.blueprint,
                    detail="unsupported remediation",
                )
            )
            continue
        _apply_files(
            root,
            result,
            finding.blueprint,
            {remediation.target: content},
            remediation.description,
        )
    _commit_manifest_or_rollback(root, result)
    if not result.changed:
        result.operation_id = None
    return result


def rollback_operation(root: Path, operation_id: str) -> ApplyResult | EvolutionReport:
    if not re.fullmatch(r"[0-9a-f]{32}", operation_id):
        raise ValueError("invalid operation id")
    manifest = root / ".blueprint-ai" / "operations" / f"{operation_id}.json"
    if not manifest.is_file():
        raise ValueError(f"unknown operation: {operation_id}")
    try:
        data = json.loads(read_text_bounded(manifest, MAX_MANIFEST_BYTES, root=root))
    except (OSError, ValueError, UnicodeError) as exc:
        raise ValueError(f"invalid operation manifest: {exc}") from exc
    if isinstance(data, dict) and data.get("version") == 3 and data.get("kind") == "evolution":
        from blueprint_ai.evolution import rollback_evolution

        return rollback_evolution(root, operation_id)
    if (
        not isinstance(data, dict)
        or type(data.get("version")) is not int
        or data.get("version") not in {1, 2}
        or data.get("operation_id") != operation_id
    ):
        raise ValueError("operation manifest identity or version does not match")
    changes = data.get("changes")
    directories = data.get("created_directories", [])
    # Receipts are mutable project files. Validate every row before deleting any file.
    if (
        not isinstance(changes, list)
        or any(
            not isinstance(row, dict)
            or not isinstance(row.get("target"), str)
            or not isinstance(row.get("blueprint"), str)
            or not isinstance(row.get("sha256"), str)
            or not re.fullmatch(r"[0-9a-f]{64}", row["sha256"])
            for row in changes
        )
        or not isinstance(directories, list)
        or any(not isinstance(value, str) for value in directories)
    ):
        raise ValueError("invalid operation manifest changes or created directories")
    result = ApplyResult(
        operation_id=operation_id, manifest_path=manifest.relative_to(root).as_posix()
    )
    for row in reversed(changes):
        relative = str(row.get("target", ""))
        target = _safe_target(root, relative)
        if target is None:
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=str(row.get("blueprint", "rollback")),
                    detail="unsafe target path or symbolic link preserved",
                )
            )
            continue
        if not target.is_file():
            result.changes.append(
                Change(
                    target=relative,
                    status="skipped",
                    blueprint=str(row.get("blueprint", "rollback")),
                    detail="created file is already absent",
                )
            )
            continue
        if not _matches_created_file(root, target, row.get("sha256")):
            result.changes.append(
                Change(
                    target=relative,
                    status="conflicted",
                    blueprint=str(row.get("blueprint", "rollback")),
                    detail="file changed after apply; preserved",
                )
            )
            continue
        target.unlink()
        result.changes.append(
            Change(
                target=relative,
                status="rolled_back",
                blueprint=str(row.get("blueprint", "rollback")),
                detail="removed unchanged file created by operation",
            )
        )
    if data.get("version") == 2 and not any(c.status == "conflicted" for c in result.changes):
        manifest.unlink()
        _remove_empty_created_directories(root, data.get("created_directories", []))
    return result
