"""Project canonical support data into CLI and documentation views without registry cycles."""

from __future__ import annotations

from blueprint_ai.support import FAMILIES, PROVIDERS, TOOLS


def support_data() -> dict:
    from blueprint_ai.adapters.registry import known_tools
    from blueprint_ai.discovery.graph import MANIFEST_LANGUAGES
    from blueprint_ai.discovery.project import LANGUAGE_SUFFIXES
    from blueprint_ai.genesis.capabilities import CAPABILITIES
    from blueprint_ai.remediation import KITS

    adapters = {a.name: a for a in known_tools()}
    tool_rows = {}
    for name, spec in TOOLS.items():
        adapter = adapters.get(name)
        tool_rows[name] = {
            **spec.model_dump(mode="json"),
            "parser": adapter.parser.__name__
            if adapter
            else ("dynamic review route" if spec.integration == "review" else spec.integration),
            "executable": adapter.executable if adapter else name,
            "network_required": adapter.network_required if adapter else None,
            "executes_project_code": adapter.executes_project_code if adapter else None,
            "timeout_seconds": (adapter.default_timeout or 120) if adapter else 120,
            "output_bytes": adapter.max_output_bytes if adapter else 4_000_000,
        }
    return {
        "schema_version": "1.0",
        "recognition_languages": sorted(
            set(LANGUAGE_SUFFIXES.values()) | set(MANIFEST_LANGUAGES.values())
        ),
        "families": {k: v.model_dump(mode="json") for k, v in FAMILIES.items()},
        "tools": tool_rows,
        "providers": {k: v.model_dump(mode="json") for k, v in PROVIDERS.items()},
        "capabilities": {k: v.model_dump(mode="json") for k, v in CAPABILITIES.items()},
        "addable": {
            k: {
                "files": list(v.files),
                "verification": v.verification,
                "alternative_files": v.alternative_files,
                "alternative_json_sections": v.alternative_json_sections,
                "mode": "create-only transaction",
            }
            for k, v in KITS.items()
        },
    }


def support_markdown() -> str:
    data = support_data()
    lines = [
        "# Support registry",
        "",
        "Generated by `blueprint-ai support --markdown`; do not edit this table manually.",
        "",
        (
            "Recognition, initialization and verification are separate cl"
            "aims. External tools require an available executable/image a"
            "nd the operator's execution policy. `supported` does not cer"
            "tify every platform or production readiness."
        ),
        "",
        "| Family | Language | Recognize | Initialize | Verifiers | Maturity | "
        "Provider / boundary |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for family in FAMILIES.values():
        provider = (
            f"[upstream]({family.provider})"
            if family.provider.startswith("https://")
            else family.provider
        )
        verifiers = ", ".join(family.verify) or (
            "built-in checks" if family.initialize else "none declared"
        )
        lines.append(
            f"| {family.id} | {family.language} | {'yes' if family.recognize else 'no'} | "
            f"{'yes' if family.initialize else 'no'} | {verifiers} | "
            f"{family.maturity} | {provider}; {family.boundary} |"
        )
    lines += [
        "",
        "## External tools",
        "",
        "| Tool | Integration / maturity | Source / license | Version policy | Acquisition |",
        "| --- | --- | --- | --- | --- |",
    ]
    for tool in TOOLS.values():
        acquisition = (
            f"`tools install {tool.id}`: `{tool.image}`; resolved image ID retained"
            if tool.image
            else tool.acquisition
        )
        lines.append(
            f"| {tool.id} | {tool.integration} / {tool.maturity} | "
            f"[upstream]({tool.source}); {tool.license} | "
            f"{tool.versions} | {acquisition} |"
        )
    lines += [
        "",
        "## Addable capabilities",
        "",
        "| Capability | Created files | Conflicting alternatives | Verification |",
        "| --- | --- | --- | --- |",
    ]
    for name, kit in data["addable"].items():
        verification = "; ".join(" ".join(c) for c in kit["verification"])
        alternatives = kit["alternative_files"] + [
            f"{file}#{section}" for file, section in kit["alternative_json_sections"].items()
        ]
        lines.append(
            f"| {name} | {', '.join(kit['files'])} | "
            f"{', '.join(alternatives) or 'same-path conflicts'} | "
            f"{verification or 'bounded structural validation'} |"
        )
    return "\n".join(lines) + "\n"
